/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

DROP PROCEDURE IF EXISTS `sp_EncodePassword`;
DELIMITER //
CREATE PROCEDURE `sp_EncodePassword`(IN `raw` VARCHAR(255), IN `salt` VARCHAR(255))
BEGIN
SELECT SHA1(CONCAT(raw,'{',salt,'}'));
END//
DELIMITER ;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
