/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

DROP PROCEDURE IF EXISTS `sp_FindGalaxyByName`;
DELIMITER //
CREATE PROCEDURE `sp_FindGalaxyByName`(IN `in_name` VARCHAR(50))
BEGIN
SELECT * FROM galaxy WHERE name = in_name LIMIT 1;
END//
DELIMITER ;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
