enum BuffAttributeCRC
{
	opAttributeStomach_drink	=   0xB9BC47C4,
	opAttributeUses_Remaining	=	0x1E497382,
	opAttributeAttr_Health		=	0x446B4174,
	opAttributeAttr_Mind		=	0xE54F80BB,
	opBACRC_PerformanceMind		=	0x11C1772E,
	opBACRC_PerformanceFocus	=	0x2E77F586,
	opBACRC_PerformanceWill		=	0x3EC6FCB6

};
enum BuffAttributeEnum
{
	Drink_Filling,
	Food_Filling,
	Health,
	Strength,
	Constitution,
	Action,
	Quickness,
	Stamina,
	Mind,
	Focus,
	Willpower,
	Burst_Run_Timer,
	Burst_Run_Cost_Reduction,
	To_Hit_Chance,
	Crafting_Assembly,
	Entertainer_Buff_Timer_Reduction,
	Timer_Reduction_on_Fire_DOT,
	Timer_Reduction_on_Bleed_DOT,
	Timer_Reduction_on_Poison_DOT,
	Timer_Reduction_on_Disease_DOT,
	DOT_Avoidance_Chance_Fire,
	DOT_Avoidance_Chance_Bleed,
	DOT_Avoidance_Chance_Poison,
	DOT_Avoidance_Chance_Disease,
	Heat_Damage_Reduction_Percent,
	Experimentation_Chance,
	Damage_Reduction_Percent,
	Constitution_Regen_Percent,
	Incap_Timer_Reduction,
	Heal_Time_Reduction_Percentage,
	Accuracy,
	Carbine_Accuracy,
	Carbine_Speed,
	Mask_Scent,
	Onehandmelee_Accuracy,
	Onehandmelee_Speed,
	Pistol_Accuracy,
	Pistol_Speed,
	Polearm_Accuracy,
	Polearm_Speed,
	Rifle_Accuracy,
	Rifle_Speed,
	Thrown_Accuracy,
	Thrown_Speed,
	Twohandmelee_Accuracy,
	Twohandmelee_Speed,
	Unarmed_Accuracy,
	Unarmed_Speed,
	Spice_Downer_Time_Reduction,
	Enhance_Wookie_Roar_Ability,
	Mission_Timer
};
