/*
---------------------------------------------------------------------------------------
This source file is part of SWG:ANH (Star Wars Galaxies - A New Hope - Server Emulator)

For more information, visit http://www.swganh.com

Copyright (c) 2006 - 2010 The SWG:ANH Team
---------------------------------------------------------------------------------------
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
---------------------------------------------------------------------------------------
*/

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

use swganh;

--
-- Definition of table `biography_planet`
--

DROP TABLE IF EXISTS `biography_planet`;
CREATE TABLE `biography_planet` (
  `planet` char(255) NOT NULL default '',
  PRIMARY KEY  (`planet`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=REDUNDANT;

--
-- Dumping data for table `biography_planet`
--

/*!40000 ALTER TABLE `biography_planet` DISABLE KEYS */;
INSERT INTO `biography_planet` (`planet`) VALUES 
 ('23 Mere'),
 ('Aaeton'),
 ('Aaghra'),
 ('Aar'),
 ('Aargau'),
 ('Aargonar'),
 ('Aaris I'),
 ('Aaris II'),
 ('Aaris III'),
 ('Ab\'Bshingh'),
 ('Abanol'),
 ('Abatrarg'),
 ('Abbaji'),
 ('Abhean'),
 ('Abo Dreth'),
 ('Abonshee'),
 ('Abraxas'),
 ('Abraxin'),
 ('Abregado-Dai'),
 ('Abregado-Fus'),
 ('Abregado-rae'),
 ('Abregado-San'),
 ('Abregado-Taki'),
 ('Abridon'),
 ('Abrion Major'),
 ('Absit'),
 ('Abyssissa'),
 ('Acatal'),
 ('Acherin'),
 ('Achillea'),
 ('Acilaris'),
 ('Acorvus'),
 ('Adamastor'),
 ('Adari'),
 ('Adarlon'),
 ('Adim'),
 ('Adin'),
 ('Adinai'),
 ('Adner'),
 ('Adriana'),
 ('Aduba-1'),
 ('Aduba-2'),
 ('Aduba-3'),
 ('Aduba-4'),
 ('Aduba-5'),
 ('Aduba-6'),
 ('Adumar'),
 ('Aefao'),
 ('Aesolian'),
 ('Aeten I'),
 ('Aeten II'),
 ('Af\'El'),
 ('Affa'),
 ('Agamar'),
 ('Agon Nine'),
 ('Agora'),
 ('Agridorn'),
 ('Agriworld-2079'),
 ('Aguarl III'),
 ('Ahlenn'),
 ('Ahug'),
 ('Aida'),
 ('Aikhibba'),
 ('Akana'),
 ('Akatoa'),
 ('Akrit\'tar'),
 ('Akuria II'),
 ('Alabash'),
 ('Alaris'),
 ('Alashan'),
 ('Alassa Major'),
 ('Alba-16'),
 ('Albecus'),
 ('Albrae-Don'),
 ('Alc'),
 ('Alderaan'),
 ('Alderath'),
 ('Aldereen(planet)'),
 ('Aldivy'),
 ('Aldraig IV'),
 ('Aleen'),
 ('Aleron'),
 ('Algara II'),
 ('Algara V'),
 ('Algara VI'),
 ('Algor'),
 ('Alion'),
 ('Alis Point'),
 ('Alisandor'),
 ('Alk\'lellish III'),
 ('Alkur'),
 ('Allandor'),
 ('Alliga'),
 ('Alluuvia'),
 ('Allyuen'),
 ('Almak'),
 ('Almania'),
 ('Almar'),
 ('Almas'),
 ('Alorthas'),
 ('Alpheridies'),
 ('Alsakan'),
 ('Altair 3'),
 ('Altair 9'),
 ('Altarrn'),
 ('Altawar'),
 ('Althir'),
 ('Altier'),
 ('Altor 14'),
 ('Altora'),
 ('Altratonne'),
 ('Altrax'),
 ('Altyr 5'),
 ('Alurion'),
 ('Alvor'),
 ('Alvorine'),
 ('Alzar'),
 ('Alzoc III'),
 ('Amador'),
 ('Amara'),
 ('Amarin'),
 ('Ambria'),
 ('Amfar'),
 ('Ammuud'),
 ('Amorphia'),
 ('Amorris'),
 ('Ampliquen'),
 ('Amrap'),
 ('Amthau'),
 ('Anantapar'),
 ('Ananuru'),
 ('Anarak Four'),
 ('Anaxes'),
 ('Anchoron'),
 ('Andalia'),
 ('Andando'),
 ('Andara'),
 ('Andasala'),
 ('Andinri'),
 ('Ando'),
 ('Ando Prime'),
 ('Andooweel'),
 ('Andosha II'),
 ('Andowyne'),
 ('Andra'),
 ('Anemcoro'),
 ('Angratha'),
 ('Anic'),
 ('Ank Ki\'Shor'),
 ('Ank Kit\'aar'),
 ('Ankus'),
 ('Annaj'),
 ('Annoo'),
 ('Anoat'),
 ('Anobis'),
 ('Anoth'),
 ('Ansarra'),
 ('Ansek'),
 ('Ansillivog'),
 ('Ansion'),
 ('Antar'),
 ('Antared III'),
 ('Antares'),
 ('Anteevy'),
 ('Antemeridias'),
 ('Antipose IX'),
 ('Antipose XII'),
 ('Antiquity'),
 ('Antmuel VI'),
 ('Anturus'),
 ('Anx Minor'),
 ('Anzat'),
 ('Apatros'),
 ('Aphran IV'),
 ('Apliria'),
 ('Aquaris'),
 ('Aquella'),
 ('Aquilae'),
 ('Aquilaris'),
 ('Arabanth'),
 ('Aracara'),
 ('Aradian'),
 ('Aralia'),
 ('Aram'),
 ('Arami'),
 ('Arapia'),
 ('Arat Fraca'),
 ('Arbra'),
 ('Arbran I'),
 ('Arbran III'),
 ('Arbran IV'),
 ('Arbran V'),
 ('Arbran VI'),
 ('Arcadia'),
 ('Arcan IV'),
 ('Archae Teuthis'),
 ('Arcopola'),
 ('Arcura'),
 ('Arda-1'),
 ('Arda-2'),
 ('Arda-3'),
 ('Arden'),
 ('Argai'),
 ('Arganu'),
 ('Argavat'),
 ('Argazda'),
 ('Argoon'),
 ('Argovia'),
 ('Aridus'),
 ('Aris'),
 ('Aris V'),
 ('Arjus'),
 ('Arkania'),
 ('Arkanis'),
 ('Arkonne III'),
 ('Armath'),
 ('Arodoni'),
 ('Arorua'),
 ('Arrakan'),
 ('Arramanx'),
 ('Arrgaw'),
 ('Arro'),
 ('Arsteni'),
 ('Arthon'),
 ('Artus Prime'),
 ('Aruza'),
 ('Arzid'),
 ('Asation'),
 ('Ash'),
 ('Ashas Ree'),
 ('Ashash'),
 ('Asher III'),
 ('Asimuse'),
 ('Askaj'),
 ('Asmall'),
 ('Asmeru'),
 ('Asran'),
 ('Asrat'),
 ('Ast Kikorie'),
 ('Atapap One'),
 ('Ather'),
 ('Athiss'),
 ('Atloran'),
 ('Ator'),
 ('Atraken'),
 ('Atrisia'),
 ('Atrivis 7'),
 ('Attahox'),
 ('Atzerri'),
 ('Aurea'),
 ('Averam'),
 ('Averill'),
 ('Aviles Prime'),
 ('Aviprine'),
 ('Avirandel'),
 ('Avishan'),
 ('Avon'),
 ('Avum'),
 ('Axion'),
 ('Axtria'),
 ('Axum'),
 ('Axxila'),
 ('Azameen'),
 ('Azbrian'),
 ('Azna'),
 ('Aztubek'),
 ('Azure'),
 ('B\'Knos'),
 ('Ba\'Har'),
 ('Babali'),
 ('Babbadod'),
 ('Babygnon'),
 ('Bacrana'),
 ('Bador'),
 ('Baes Logia'),
 ('Baffop'),
 ('Bak'),
 ('Bakarr'),
 ('Bakkah'),
 ('Bakura'),
 ('Bakura-5'),
 ('Bakura-6'),
 ('Bakura-7'),
 ('Bakura-8'),
 ('Bal\'demnic'),
 ('Bala'),
 ('Balamak'),
 ('Balanor'),
 ('Balfron'),
 ('Balis-Baurgh'),
 ('Balmorra'),
 ('Balosar'),
 ('Balowa'),
 ('Baltimn'),
 ('Baltizaar'),
 ('Ban-Satir II'),
 ('Bancar'),
 ('Bandomeer'),
 ('Bandonia'),
 ('Barab I'),
 ('Barab II'),
 ('Barab III'),
 ('Baraboo'),
 ('Baradas II'),
 ('Baralou'),
 ('Baramorra'),
 ('Barcola'),
 ('Barenth'),
 ('Barhu'),
 ('Barison'),
 ('Barkhesh'),
 ('Barlok'),
 ('Barmasel'),
 ('Barnaba'),
 ('Baroli'),
 ('Baroonda'),
 ('Baros'),
 ('Barpine'),
 ('Barseg'),
 ('Barundi'),
 ('Basho'),
 ('Basilisk'),
 ('Baskarn'),
 ('Bassadro'),
 ('Basteel'),
 ('Bastion'),
 ('Batorine'),
 ('Bavva'),
 ('Bazaar'),
 ('Beauchen'),
 ('Beckoning Call Starr 3'),
 ('Bedara'),
 ('Begeren'),
 ('Beheboth'),
 ('Behenui'),
 ('Belasco'),
 ('Belazura'),
 ('Belderone'),
 ('Belgaroth'),
 ('Belkadan'),
 ('Bellassa'),
 ('Bellatrig'),
 ('Bellis IV'),
 ('Belnar'),
 ('Belorphyn'),
 ('Belovia'),
 ('Belsavis'),
 ('Belshar Othacuu'),
 ('Belsmuth II'),
 ('Belthu'),
 ('Beltrix III'),
 ('Bendeluum'),
 ('Bendone'),
 ('Beneris'),
 ('Bengat'),
 ('Bengely'),
 ('Benja-Rihn'),
 ('Benon'),
 ('Berason'),
 ('Berchest'),
 ('Berea'),
 ('Berri'),
 ('Berrol\'s Donn'),
 ('Berrun'),
 ('Berusa'),
 ('Besberra'),
 ('Bescane'),
 ('Besn'),
 ('Bespin'),
 ('Bessimir'),
 ('Bestal III'),
 ('Bestine IV'),
 ('Beta Olikark'),
 ('Beta Rhama'),
 ('Betal'),
 ('Betha II'),
 ('Bethal'),
 ('Bethany'),
 ('Bethars'),
 ('Betolio'),
 ('Betshish'),
 ('Bettok'),
 ('Bevell III'),
 ('Bextar'),
 ('Bezim'),
 ('Bhuna Sound'),
 ('Bianas'),
 ('Biewa'),
 ('Biitu'),
 ('Biivren'),
 ('Bilagen'),
 ('Bilios'),
 ('Bimin Three'),
 ('Bimmiel'),
 ('Bimmisaari'),
 ('Binaros'),
 ('Binquaros'),
 ('Biolag'),
 ('Biosh'),
 ('Birjis'),
 ('Blathar III'),
 ('Blenjeel'),
 ('Blimph 3'),
 ('Blyte'),
 ('Bnach'),
 ('Bnar VII'),
 ('Boden'),
 ('Bodrin'),
 ('Bofa II'),
 ('Bogden'),
 ('Bogo Rai'),
 ('Bolad'),
 ('Bomis Korri IV'),
 ('Bonadan'),
 ('Bondar'),
 ('Boonta'),
 ('Boordii'),
 ('Boranall'),
 ('Borao'),
 ('Borcorash'),
 ('Bordal'),
 ('Borgo Prime'),
 ('Borkyne'),
 ('Borleias'),
 ('Borlov'),
 ('Bormter'),
 ('Borosk'),
 ('Bortras'),
 ('Bosch'),
 ('Bosph'),
 ('Bosthirda'),
 ('Botajef'),
 ('Bothawui'),
 ('Botor'),
 ('Boudolayz'),
 ('Bovo Yagen'),
 ('Boz Pity'),
 ('Boztrok'),
 ('Bpfassh'),
 ('Brachnis Chorios'),
 ('Bragkis'),
 ('Branteez'),
 ('Branth'),
 ('Brath Qella'),
 ('Breeka'),
 ('Brentaal'),
 ('Brenu'),
 ('Bresallis'),
 ('Bresan'),
 ('Breshkall'),
 ('Bresnia'),
 ('Bretta'),
 ('Brevost'),
 ('Bri\'ahl'),
 ('Bridin Anchorage'),
 ('Brigia'),
 ('Brintooin'),
 ('Brochiib'),
 ('Brodo Asogi'),
 ('Broest'),
 ('Brolsam'),
 ('Bront'),
 ('Brosi'),
 ('Brugga'),
 ('Bryexx'),
 ('Bryndar'),
 ('Bryx'),
 ('Bseto I'),
 ('Buamlon Central'),
 ('Budpock'),
 ('Bundim'),
 ('Bunduki'),
 ('Burnin Konn'),
 ('Burska'),
 ('Bursol II'),
 ('Butler\'s Cove'),
 ('Byblos'),
 ('Byss'),
 ('C-Foroon'),
 ('Caamas'),
 ('Caamor'),
 ('Caaraz'),
 ('Caarimon'),
 ('Cadezia'),
 ('Cadinth'),
 ('Cadomai Prime'),
 ('Cal-Seti'),
 ('Calabosh-2'),
 ('Calfa-5'),
 ('Calipp'),
 ('Calipsa'),
 ('Calline I'),
 ('Calline II'),
 ('Calline III'),
 ('Callonia'),
 ('Calonica'),
 ('Caloria'),
 ('Caltinia'),
 ('Calus'),
 ('Caluula'),
 ('Camden'),
 ('Camos'),
 ('Canastra IV'),
 ('Canoliss IV'),
 ('Canti'),
 ('Cantras Gola'),
 ('Cantros 7'),
 ('Canyon'),
 ('Caprioril'),
 ('Caprol'),
 ('Capza'),
 ('Caramm V'),
 ('Cardooine'),
 ('Carest 1'),
 ('Cargamalis'),
 ('Cari'),
 ('Carida'),
 ('Carnth'),
 ('Carosi IV'),
 ('Carosi IX'),
 ('Carosi VI'),
 ('Carosi VII'),
 ('Carosi VIII'),
 ('Carosi X'),
 ('Carosi XI'),
 ('Carosi XII'),
 ('Carratos'),
 ('Carrivar'),
 ('Carsanza'),
 ('Cartao'),
 ('Carz'),
 ('Casfield 6'),
 ('Casna Aure'),
 ('Casna Besh'),
 ('Cassander'),
 ('Castell'),
 ('Cathar'),
 ('Cathis'),
 ('Cato Neimoidia'),
 ('Cattamascar'),
 ('Cauper'),
 ('Caursito'),
 ('Cavas'),
 ('Cejansij'),
 ('Celanon'),
 ('Celdaru'),
 ('Celegia'),
 ('Centares'),
 ('Centurious'),
 ('Cerea'),
 ('Ceriun'),
 ('Cesya'),
 ('Ceti 597'),
 ('Ch\'hodos'),
 ('Chaasch'),
 ('Chabosh'),
 ('Chadra'),
 ('Chaila'),
 ('Chalacta'),
 ('Chalcedon'),
 ('Challon'),
 ('Chamble'),
 ('Champala'),
 ('Chandaar'),
 ('Chandrila'),
 ('Chanj'),
 ('Chardaan'),
 ('Charenthoth'),
 ('Charis'),
 ('Charmath'),
 ('Charny'),
 ('Charros IV'),
 ('Charubah'),
 ('Chateuse VII'),
 ('Chav'),
 ('Chazwa'),
 ('Cheelit'),
 ('Cheeyoom Matee'),
 ('Chel'),
 ('Chibias'),
 ('Chirgay'),
 ('Chiron'),
 ('Choi'),
 ('Cholganna'),
 ('Chommell Minor'),
 ('Chorax'),
 ('Chortose'),
 ('Chrellis'),
 ('Chroma Zed'),
 ('Chromovon'),
 ('Chrona'),
 ('Chrondre'),
 ('Chryya'),
 ('Chule'),
 ('Churba'),
 ('Churruma'),
 ('Cificap VII'),
 ('Cilpar'),
 ('Cinnatar'),
 ('Circarpous IV'),
 ('Circarpous X'),
 ('Circarpous XII'),
 ('Circarpous XIV'),
 ('Cirra'),
 ('Cirrus'),
 ('Cirus II'),
 ('Ciutric'),
 ('Claer'),
 ('Clak\'Dor I'),
 ('Clak\'Dor II'),
 ('Clak\'Dor III'),
 ('Clak\'Dor IV'),
 ('Clak\'Dor V'),
 ('Clak\'Dor VI'),
 ('Clak\'Dor VII'),
 ('Clantaano III'),
 ('Clar'),
 ('Clascvoria'),
 ('Clendora'),
 ('Cleroff\'s World'),
 ('Cmaoli Di'),
 ('Coachelle II'),
 ('Coachelle III'),
 ('Coachelle IV'),
 ('Coachelle Prime'),
 ('Coachelle V'),
 ('Colavas'),
 ('Colavas Minor'),
 ('Colavas Tertiary'),
 ('Colla IV'),
 ('Colossus'),
 ('Cols'),
 ('Colsa'),
 ('Columex'),
 ('Columus'),
 ('Colunda Prime'),
 ('Comkin V'),
 ('Commenor'),
 ('Comra'),
 ('Cona'),
 ('Concord Dawn'),
 ('Condular'),
 ('Constancia'),
 ('Contruum'),
 ('Contruum Six'),
 ('Conus'),
 ('Coomputu'),
 ('Coorimbus IV'),
 ('Cophrigin 5'),
 ('Cor I'),
 ('Cor II'),
 ('Cor III'),
 ('Corann'),
 ('Corbos'),
 ('Cordes'),
 ('Corellia'),
 ('Corfai'),
 ('Coriallis'),
 ('Corjain'),
 ('Corlass'),
 ('Corlax 4'),
 ('Coronar'),
 ('Corri'),
 ('Corroth'),
 ('Corsin'),
 ('Corstris'),
 ('Cortella'),
 ('Cortina'),
 ('Corulag'),
 ('Corus'),
 ('Coruscant'),
 ('Coruscul'),
 ('Corutarn'),
 ('Corva'),
 ('Corva Yag'),
 ('Corvanni IV'),
 ('Corvis Minor 3'),
 ('Corvis Minor 4'),
 ('Corvis Minor 5'),
 ('Cotellier'),
 ('Council'),
 ('Courkrus'),
 ('Coveway'),
 ('Coyn'),
 ('Craci'),
 ('Crakull'),
 ('Cranan 12'),
 ('Crella'),
 ('Cridark II'),
 ('Criton\'s Point'),
 ('Crollia'),
 ('Crustai II'),
 ('Crytal Nest'),
 ('Csilla'),
 ('Cuirilla'),
 ('Cujicor'),
 ('Cularin'),
 ('Culroon III'),
 ('Cuthbern'),
 ('Cybloc'),
 ('Cyborrea'),
 ('Cygnus B'),
 ('Cyimarra'),
 ('Cyphar'),
 ('Cyrillia'),
 ('D\'Pur'),
 ('D\'rinba IV'),
 ('D\'Skar'),
 ('D\'vouran'),
 ('Da Soocha'),
 ('Da\'nor'),
 ('Daalang'),
 ('Dac(see Mon Calamari)'),
 ('Dachat'),
 ('Dadrus'),
 ('Daemen'),
 ('Dagary Minor'),
 ('Dagelin Minor'),
 ('Dagobah'),
 ('Dagro'),
 ('Dagu'),
 ('Dahvil'),
 ('Daimla'),
 ('Dajutt'),
 ('Dakot 7'),
 ('Dakshee'),
 ('Dakuyl'),
 ('Dalastine'),
 ('Dalgoni'),
 ('Dalos IV'),
 ('Dalron 5'),
 ('Dalron IV'),
 ('Daltar'),
 ('Daluba'),
 ('Daluuj'),
 ('Daminia'),
 ('Damonite Yors-B'),
 ('Dampher'),
 ('Damualer Triac'),
 ('Danadine'),
 ('Danalbeth'),
 ('Danar'),
 ('Danchian Prime'),
 ('Dancreti'),
 ('Dandalas'),
 ('Dandelo'),
 ('Dandino'),
 ('Dandrian'),
 ('Dankayo'),
 ('Danoor'),
 ('Danteel'),
 ('Danton VI'),
 ('Dantooine'),
 ('Danuta'),
 ('Danzer'),
 ('Dar'),
 ('Dar\'Or'),
 ('Darada'),
 ('Darepp'),
 ('Dargul'),
 ('Dargulli'),
 ('Darkknell'),
 ('Darkon III'),
 ('Darlon'),
 ('Darlyn Boda'),
 ('Daroon'),
 ('Darsie'),
 ('Darstell 4'),
 ('Dartessex IV'),
 ('Daslkehnt'),
 ('Datar'),
 ('Dathomir'),
 ('Daupherm'),
 ('Daver Kuat'),
 ('Davirien'),
 ('Davnar II'),
 ('De\'nel'),
 ('Dega'),
 ('DeGerrillion'),
 ('Deko Neimoidia'),
 ('Dela III'),
 ('Delanoth'),
 ('Delantine'),
 ('Delari Prime'),
 ('Delassin VI'),
 ('Delaya'),
 ('Delderaan'),
 ('Delemede'),
 ('Dellalt'),
 ('Delle II'),
 ('Delphon'),
 ('Delrakkin'),
 ('Delrian'),
 ('Deltooine'),
 ('Demar'),
 ('Demesel'),
 ('Demigue'),
 ('Deminol'),
 ('Demnadi'),
 ('Demonsgate'),
 ('Demophon'),
 ('Demos Four'),
 ('Denab'),
 ('Denava'),
 ('Denbalen'),
 ('Denbo'),
 ('Deneba'),
 ('Deneter'),
 ('Denevar'),
 ('Dennaskar'),
 ('Denon'),
 ('Dentaal'),
 ('Denubba'),
 ('Denuhi VIII'),
 ('Deralia'),
 ('Derenath'),
 ('Derf'),
 ('Derilyn'),
 ('Derr'),
 ('Derra IV'),
 ('Derricon'),
 ('Derson III'),
 ('Desargorr'),
 ('Desevro'),
 ('Despayre'),
 ('Desstius'),
 ('Destreg II'),
 ('Destrillion'),
 ('Devaron'),
 ('Devato'),
 ('Devon Four'),
 ('Deyer'),
 ('Deylerax'),
 ('Deysum III'),
 ('Dhorian'),
 ('Di\'tai\'ni'),
 ('Di\'wor'),
 ('Dilbana'),
 ('Dilonexa XXIII'),
 ('Dimok'),
 ('Din'),
 ('Dinlo'),
 ('Disim'),
 ('Dithanune'),
 ('Dix\'thaar'),
 ('Djurmo'),
 ('Dles IV'),
 ('Dlor 3'),
 ('DNX-N1'),
 ('Doaskin'),
 ('Dodz'),
 ('Dohlban'),
 ('Dohu VII'),
 ('Doldur'),
 ('Doli'),
 ('Dolis 3'),
 ('Dolla'),
 ('Dolomar'),
 ('Dolstan'),
 ('Dolucar'),
 ('Dom-Bradden'),
 ('Domgrin'),
 ('Don I'),
 ('Don II'),
 ('Donadus'),
 ('Doneer\'so'),
 ('Doniphon'),
 ('Donoa'),
 ('Dononter Minor'),
 ('Donovia'),
 ('Dontamo'),
 ('Doornik-1142'),
 ('Doornik-207'),
 ('Doornik-628A'),
 ('Doornik-628B'),
 ('Doornik-628C'),
 ('Doornik-628F'),
 ('Doornik-628G'),
 ('Doornik-628H'),
 ('Dor'),
 ('Dor Nameth'),
 ('Dorajan'),
 ('Dorande'),
 ('Dorcin'),
 ('Dordolum'),
 ('Dorella'),
 ('Dorellia'),
 ('Dorin'),
 ('Doris'),
 ('Dorlo'),
 ('Dorlon II'),
 ('Dornea'),
 ('Dorriella'),
 ('Dorsis'),
 ('Dorumaa'),
 ('Dorvalla'),
 ('Dorvalla IV'),
 ('Dosuun'),
 ('Douglas III'),
 ('Doulos'),
 ('Dra III'),
 ('Drackmar'),
 ('Draenell\'s Point'),
 ('Draethos'),
 ('Dragos VI'),
 ('Drall'),
 ('Draria'),
 ('Draukyze'),
 ('Dravione'),
 ('Dreena'),
 ('Dreffon IV'),
 ('Drefni'),
 ('Dremulae'),
 ('Dressel'),
 ('Dreve'),
 ('Drexel II'),
 ('Drgi'),
 ('Droecil'),
 ('Drog II'),
 ('Drogheda'),
 ('Dromund Fels'),
 ('Dromund Ixin'),
 ('Dromund Kaas'),
 ('Dromund Kalakar'),
 ('Dromund Tyne'),
 ('Drong II'),
 ('Drongar'),
 ('Dronseen'),
 ('Droxine'),
 ('Droxu'),
 ('Druckenwell'),
 ('Drup I'),
 ('Drup II'),
 ('Drup III'),
 ('Du Hatta'),
 ('Dubrava'),
 ('Dubrillion'),
 ('Duconon'),
 ('Dulathia'),
 ('Dulin'),
 ('Duneeden'),
 ('Dur Sabon'),
 ('Durgeon'),
 ('Durkteel'),
 ('Duro'),
 ('Duron'),
 ('Duroon'),
 ('Durren'),
 ('Duunir'),
 ('Dweem'),
 ('Dwi\'kar'),
 ('Dwi\'lar'),
 ('Dwor'),
 ('Dzass IV'),
 ('Ealor'),
 ('Ebaq'),
 ('Ebiwaan'),
 ('Ebra'),
 ('Ec Pand'),
 ('Eckless'),
 ('Eclipse'),
 ('Eczar'),
 ('Edan II'),
 ('Edatha'),
 ('Ediorung'),
 ('Edonaaris'),
 ('Eedoq'),
 ('Eeropha'),
 ('Eeyyon'),
 ('Ehjenla'),
 ('Eiattu 6'),
 ('Eirrauus'),
 ('Eislomi III'),
 ('Ejolus'),
 ('Ekibo'),
 ('Elatha'),
 ('Elbara Nine'),
 ('Elcorth'),
 ('Elerion'),
 ('Eliad'),
 ('Elin Roe'),
 ('Eloggi'),
 ('Elokas'),
 ('Elom'),
 ('Elpur'),
 ('Elrood'),
 ('Elshandruu Pica'),
 ('Elsho'),
 ('Embaril'),
 ('Ember'),
 ('Emberlene'),
 ('Emet'),
 ('Emmer'),
 ('Empress Teta'),
 ('Emra'),
 ('Enaleh'),
 ('Enarc'),
 ('Endex'),
 ('Endor'),
 ('Endoraan'),
 ('Endovan'),
 ('Endregaad'),
 ('Enenpa'),
 ('Enet'),
 ('Engebo V'),
 ('Engira'),
 ('Enisca'),
 ('Enkep'),
 ('Ennth'),
 ('Entralla'),
 ('Entrus'),
 ('Entuur'),
 ('Eol Sha'),
 ('Eos'),
 ('Ephemera'),
 ('Epsi Nadir'),
 ('Equanus'),
 ('Er\'Kit'),
 ('Er\'stacia'),
 ('Erai'),
 ('Eredenn Prime'),
 ('Eredin'),
 ('Erep'),
 ('Eres III'),
 ('Ergeshui'),
 ('Ergo'),
 ('Eriadu'),
 ('Erigorm'),
 ('Erilnar'),
 ('Eriscot'),
 ('Ertegas'),
 ('Erysthes'),
 ('Escabar'),
 ('Esfandia'),
 ('Eskaron'),
 ('Esooma'),
 ('Esseles'),
 ('Ession'),
 ('Essowyn'),
 ('Estaph'),
 ('Etorasp'),
 ('Etti IV'),
 ('Euceron'),
 ('Euton'),
 ('Evas VI'),
 ('Excarga'),
 ('Exocron'),
 ('Exodeen'),
 ('Exodo II'),
 ('Expora'),
 ('Eyrie'),
 ('Eyttyrmin'),
 ('F\'Dann IX'),
 ('F\'Tang'),
 ('F\'tral'),
 ('Faa'),
 ('Faargau'),
 ('Fadden'),
 ('Fahul'),
 ('Fait d\'Fait'),
 ('Fakir'),
 ('Fal'),
 ('Falang Minor'),
 ('Faldos'),
 ('Falk'),
 ('Falleen'),
 ('Fangol'),
 ('Far Qasqi'),
 ('Farbog'),
 ('Farboon'),
 ('Farfeld II'),
 ('Farrfin'),
 ('Farsellah'),
 ('Farstey'),
 ('Farstine'),
 ('Faz'),
 ('Fedalle'),
 ('Fedje'),
 ('Feenicks VI'),
 ('Fef'),
 ('Fehern'),
 ('Felacat'),
 ('Felucia'),
 ('Fendry'),
 ('Fengrine'),
 ('Fenion'),
 ('Fenn'),
 ('Fennesa'),
 ('Fenves'),
 ('Fere'),
 ('Feriae Junction'),
 ('Ferrhast'),
 ('Ferro'),
 ('Ferros VI'),
 ('Ferxani'),
 ('Fest'),
 ('Fether'),
 ('Fibuli'),
 ('Fiddanl'),
 ('Filo'),
 ('Filordis'),
 ('Filve'),
 ('Findris'),
 ('Firrerre'),
 ('Firro'),
 ('Fishur'),
 ('Fislan'),
 ('Fitca Prime'),
 ('Flandar'),
 ('Flankers'),
 ('Flax'),
 ('Fleyars IV'),
 ('Flitter'),
 ('Florn'),
 ('Flotsam'),
 ('Floubette'),
 ('Fluwhaka'),
 ('Fnessal'),
 ('Fodro'),
 ('Fodurant'),
 ('Foerost'),
 ('Fokask'),
 ('Foless'),
 ('Fondor'),
 ('Fondurant'),
 ('Formos'),
 ('Fornax'),
 ('Fornow'),
 ('Forscan VI'),
 ('Forsen'),
 ('Fortay'),
 ('Foundry'),
 ('Foxar'),
 ('Framesk Yagen'),
 ('Freda'),
 ('Frego'),
 ('Freliq'),
 ('Frellor'),
 ('Fremond III'),
 ('Frenoris'),
 ('Fresia'),
 ('Fretaria'),
 ('Frewwil'),
 ('Friijillis'),
 ('Frisal'),
 ('Frithia'),
 ('Froswythe'),
 ('Froz'),
 ('Fusai'),
 ('Fwatna'),
 ('Fwiis'),
 ('Fwillsving'),
 ('Fyodos'),
 ('G\'aav\'aar\'oon'),
 ('G\'Hol'),
 ('G\'rho'),
 ('G\'wenee'),
 ('Gabredor III'),
 ('Gacerian'),
 ('Gadon 3'),
 ('Gailea'),
 ('Gaios'),
 ('Gala'),
 ('Galaan'),
 ('Galand'),
 ('Galantos'),
 ('Galdar'),
 ('Gale'),
 ('Galidraan'),
 ('Galleefryn II'),
 ('Gallinore'),
 ('Galltine'),
 ('Galpos II'),
 ('Galtea'),
 ('Galvoni III'),
 ('Gama'),
 ('Gamandar'),
 ('Gambolla'),
 ('Gammalin'),
 ('Gamorr'),
 ('Ganash'),
 ('Ganath'),
 ('Gand'),
 ('Gandalla'),
 ('Gandeal'),
 ('Gandle Ott'),
 ('Gandolo'),
 ('Gandrossi VI'),
 ('Gandrun II'),
 ('Ganeid IV'),
 ('Gania'),
 ('Ganlihk'),
 ('Ganthel'),
 ('Gantho'),
 ('Gap Nine'),
 ('Garban'),
 ('Garen IV'),
 ('Gargolyn IV'),
 ('Gargon'),
 ('Garia'),
 ('Garn'),
 ('Garnib'),
 ('Garobi'),
 ('Garos IV'),
 ('Garqi'),
 ('Garrthinius'),
 ('Garsala'),
 ('Gart'),
 ('Gartana'),
 ('Garulag'),
 ('Gascon'),
 ('Gastol'),
 ('Gastrula'),
 ('Gathus'),
 ('Gaulus'),
 ('Gaurick'),
 ('Gauther'),
 ('Gavens'),
 ('Gavryn'),
 ('Gbu'),
 ('Gedi IV'),
 ('Geedon V'),
 ('Gelefil'),
 ('Gelgelar'),
 ('Gellefon'),
 ('Geminor'),
 ('Genarius'),
 ('Genassa'),
 ('Gendius V'),
 ('Gendoraan'),
 ('Generis'),
 ('Genesia'),
 ('Genian'),
 ('Genon'),
 ('Gentes'),
 ('Geonosis'),
 ('Geran'),
 ('Gerbaud 2'),
 ('Gerhalt III'),
 ('Geric IV'),
 ('Geridard'),
 ('Geriss'),
 ('Gerrard V'),
 ('Gerrenthum'),
 ('Gerres Gule'),
 ('Gertafuu VI'),
 ('Gesaril'),
 ('Gestron'),
 ('Gettiarn'),
 ('Ghishi'),
 ('Gholondreine-b'),
 ('Ghorman'),
 ('Gibbela'),
 ('Gigor'),
 ('Giju'),
 ('Gillad'),
 ('Gilliana'),
 ('Glade'),
 ('Glakka'),
 ('Glauheim'),
 ('Glee Anselm'),
 ('Gligger'),
 ('Glithnos'),
 ('Glom Tho'),
 ('Glottal'),
 ('Glova'),
 ('Gobindi'),
 ('Godo'),
 ('Godsspire'),
 ('Goelitz'),
 ('Golh'),
 ('Golkus'),
 ('Golm'),
 ('Golrath'),
 ('Goluud Minor'),
 ('Gondagali'),
 ('Gonmore'),
 ('Goratak III'),
 ('Goravas'),
 ('Gorbah'),
 ('Gorlan'),
 ('Gorm'),
 ('Gormen'),
 ('Goroth Prime'),
 ('Gorsh'),
 ('Gorta'),
 ('Gortamni'),
 ('Gorth'),
 ('Gortis'),
 ('Gosfambling'),
 ('Gotida'),
 ('Gottlegoob'),
 ('Gowdawl'),
 ('Gra Ploven'),
 ('Graal\'diin'),
 ('Graewyn'),
 ('Grakouine'),
 ('Grall'),
 ('Grandeel'),
 ('Granna'),
 ('Granus IV'),
 ('Grastes'),
 ('Grathus'),
 ('Gravan Seven'),
 ('Gravlex Med'),
 ('Greater Galam'),
 ('Greater Marianas'),
 ('Gree'),
 ('Grella'),
 ('Greyman\'s Planet'),
 ('Grizmallt'),
 ('Gromas'),
 ('Gruvia'),
 ('Gryphon'),
 ('Guiteica'),
 ('Gulma'),
 ('Gumbus'),
 ('Gymelo'),
 ('Gyndine'),
 ('Gyosha'),
 ('H\'ken'),
 ('H\'nemthe'),
 ('H\'ratth'),
 ('H\'relac'),
 ('Haariden'),
 ('Haashimut'),
 ('Habassa II'),
 ('Had Abbadon'),
 ('Hadlress'),
 ('Haffrin'),
 ('Hakassi'),
 ('Halanit'),
 ('Halbara'),
 ('Haldeen'),
 ('Hali'),
 ('Hallrin IV'),
 ('Halm'),
 ('Halmad'),
 ('Halowan'),
 ('Halpat'),
 ('Hamyl'),
 ('Hanchin'),
 ('Handooine'),
 ('Hanofar'),
 ('Hapes'),
 ('Hapuntep'),
 ('Harazod'),
 ('Harbin-re'),
 ('Hargeeva'),
 ('Harix'),
 ('Harloen'),
 ('Harpori'),
 ('Harrandarr'),
 ('Harridan'),
 ('Harrin'),
 ('Harrod\'s Planet'),
 ('Haruun Kal'),
 ('Hasaq'),
 ('Hast'),
 ('Hathrox III'),
 ('Havath Minor'),
 ('Havath Prime'),
 ('Haverling'),
 ('Havricus'),
 ('Hazzard'),
 ('Hebeth'),
 ('Hefi'),
 ('Heleth 4'),
 ('Helisk'),
 ('Hellios'),
 ('Heloan Yagen'),
 ('Helska IV'),
 ('Hemei IV'),
 ('Hensara III'),
 ('Herdessa'),
 ('Herego'),
 ('Herios IV'),
 ('Heriston'),
 ('Hern'),
 ('Herstell V'),
 ('Herzob'),
 ('Hethar'),
 ('Hettsk'),
 ('Hewl'),
 ('Hiffis'),
 ('High Chunah'),
 ('Hijarna'),
 ('Hilo'),
 ('Hino-111'),
 ('Hintivan II'),
 ('Hirin'),
 ('Hirsi'),
 ('Hishyim'),
 ('Hjaff'),
 ('Hockaleg'),
 ('Hok'),
 ('Holageus'),
 ('Hollast VII'),
 ('Hologram Fun World'),
 ('Homon'),
 ('Honoghr'),
 ('Hoppawui'),
 ('Hordon Cal'),
 ('Horn Station'),
 ('Horob'),
 ('Horska'),
 ('Horticar'),
 ('Hosrel XI'),
 ('Hoth'),
 ('Houche'),
 ('Houll'),
 ('Hovan'),
 ('Hoylin'),
 ('Hraki'),
 ('Huip'),
 ('Huk'),
 ('Hultomo'),
 ('Humbarine'),
 ('Hurcha'),
 ('Hurikane'),
 ('Hutlar'),
 ('Hyabb'),
 ('Hyder'),
 ('Hypori'),
 ('Hypotria'),
 ('Hyrol Preen Beta'),
 ('Hythrope IV'),
 ('Ibanjii'),
 ('Ichium'),
 ('Ichtor 8'),
 ('Ieria'),
 ('Ifmix VI'),
 ('Ifron'),
 ('Ignacia'),
 ('Ihopek'),
 ('Ijol'),
 ('Iktotchon'),
 ('Ilimardon'),
 ('Illarreen'),
 ('Illodia'),
 ('Illoud'),
 ('Ilum'),
 ('Imdaar'),
 ('Immalia'),
 ('Imoco'),
 ('Improcco'),
 ('Inat Prime'),
 ('Indellian'),
 ('Indikir'),
 ('Indinor'),
 ('Indoumodo'),
 ('Indrexu'),
 ('Indu San'),
 ('Indupar'),
 ('Ingo'),
 ('Inner Los'),
 ('Insta-7'),
 ('Intran'),
 ('Intuci'),
 ('Inwil'),
 ('Inysh'),
 ('Ione'),
 ('Ios'),
 ('Iotra'),
 ('Iphigin'),
 ('Iqobal'),
 ('Iqoon'),
 ('Irfan'),
 ('Iri'),
 ('Iridium'),
 ('Iridonia'),
 ('Irith'),
 ('Iscera'),
 ('Isde Naha'),
 ('Isen'),
 ('Iseno'),
 ('Ishanna I'),
 ('Ishanna II'),
 ('Ishanna V'),
 ('Isht'),
 ('Isiring'),
 ('Isis'),
 ('Iskadrell'),
 ('Iskalon'),
 ('Issarga'),
 ('Issor'),
 ('Istic II'),
 ('Ithona'),
 ('Ithoon'),
 ('Ithor'),
 ('Ithull'),
 ('Ivatch'),
 ('Ixtlar'),
 ('Iychtor'),
 ('Iyred'),
 ('Iyuta'),
 ('J\'t\'p\'tan'),
 ('Jabiim'),
 ('Jabor'),
 ('Jaemus'),
 ('Jagga II'),
 ('Jagga VII'),
 ('Jaguada'),
 ('Jalarren'),
 ('Jaminere'),
 ('Janara III'),
 ('Jandoon'),
 ('Jandur'),
 ('Jangelle'),
 ('Janguine'),
 ('Janilis VII'),
 ('Jankok'),
 ('Janodral Mizar'),
 ('Jante'),
 ('Jappe'),
 ('Jardeen IV'),
 ('Jaroona'),
 ('Jarsatt'),
 ('Jarvanam'),
 ('Jastro III'),
 ('Jatee'),
 ('Jatir'),
 ('Javaal'),
 ('Javin'),
 ('Javis'),
 ('Jaxus'),
 ('Jaymmz'),
 ('Jazbina'),
 ('Jedd 6'),
 ('Jellyfish Cove'),
 ('Jendar'),
 ('Jendorn'),
 ('Jenenma'),
 ('Jentawui'),
 ('Jerijador'),
 ('Jerne'),
 ('Jerrilek'),
 ('Jerrist VI'),
 ('Jestan'),
 ('Jestefad'),
 ('Jeyell'),
 ('Jhas'),
 ('Jhensrus'),
 ('Jiaan'),
 ('Jidlor'),
 ('Jinathik'),
 ('Jinda'),
 ('Jinet'),
 ('Jiroch-Reslia'),
 ('Jjannex II'),
 ('Jodaka'),
 ('Jofoger'),
 ('Joiol'),
 ('Jomark'),
 ('Jomon'),
 ('Joodrudda'),
 ('Joralla'),
 ('Joruna'),
 ('Jubilar'),
 ('Julsujod III'),
 ('Jumus'),
 ('Jun'),
 ('Junction 5'),
 ('Jurzan'),
 ('Jussafet Four'),
 ('Justa'),
 ('Juvex'),
 ('Jweab VII'),
 ('K\'ath'),
 ('k\'Farri'),
 ('K\'ken'),
 ('K\'taktaxka'),
 ('K\'vath 5'),
 ('K\'Zar'),
 ('Kaa'),
 ('Kaal'),
 ('Kabaira'),
 ('Kabal'),
 ('Kabieroun'),
 ('Kabray'),
 ('Kadok III-A'),
 ('Kadok III-B'),
 ('Kadok III-C'),
 ('Kadok III-E'),
 ('Kadril'),
 ('Kaellin III'),
 ('Kagstag'),
 ('Kaikielius'),
 ('Kail'),
 ('Kailion'),
 ('Kailor V'),
 ('Kaisa'),
 ('Kal\'shebbol'),
 ('Kalaan'),
 ('Kalab'),
 ('Kalandis IV'),
 ('Kalarba'),
 ('Kalee'),
 ('Kalgo 13'),
 ('Kalidorn'),
 ('Kalis'),
 ('Kaliska'),
 ('Kalist VI'),
 ('Kalki'),
 ('Kalkovalk'),
 ('Kalla VII'),
 ('Kallidah'),
 ('Kallistas'),
 ('Kalok'),
 ('Kaloo'),
 ('Kalsunor'),
 ('Kalzeron'),
 ('Kamar'),
 ('Kamino'),
 ('Kammia'),
 ('Kamori'),
 ('Kamparas'),
 ('Kamper'),
 ('Kamsul'),
 ('Kamur'),
 ('Kanaver'),
 ('Kaon'),
 ('Karatha'),
 ('Karavis'),
 ('Karazak'),
 ('Karedda'),
 ('Karfeddion'),
 ('Karideph'),
 ('Kariek'),
 ('Karinda'),
 ('Karlatt'),
 ('Karnak Alpha'),
 ('Karnst'),
 ('Karoliston'),
 ('Karra'),
 ('Karvoss II'),
 ('Kas'),
 ('Kashi'),
 ('Kashir'),
 ('Kashoonara'),
 ('Kashyyyk'),
 ('Kasiol 3'),
 ('Kassido'),
 ('Kastin'),
 ('Katanos VII'),
 ('Katarr'),
 ('Kathol'),
 ('Katorr'),
 ('Katraasii'),
 ('Kattada'),
 ('Kaump III'),
 ('Kauron'),
 ('Kayri III'),
 ('Kazlin 5'),
 ('Keedad'),
 ('Kegan'),
 ('Kejim'),
 ('Kelada'),
 ('Kelarea'),
 ('Kelliadu'),
 ('Kelro'),
 ('Kelrodo-Ai'),
 ('Keltos IV'),
 ('Kemplex'),
 ('Kendamar'),
 ('Kerensik'),
 ('Keres I'),
 ('Keres II'),
 ('Kerest'),
 ('Keriba'),
 ('Kerig\'En'),
 ('Kerilt'),
 ('Keryt'),
 ('Kes'),
 ('Keskin'),
 ('Kessel'),
 ('Kestos Minor'),
 ('Ket'),
 ('Ketal'),
 ('Ketaris'),
 ('Kevron'),
 ('Keyorin'),
 ('Khar Delba'),
 ('Kharzet III'),
 ('Kheedar'),
 ('Kho Nai'),
 ('Kholes'),
 ('Khomm'),
 ('Kich'),
 ('Kidiet Olgo'),
 ('Kidriff 5'),
 ('Kidron'),
 ('Kiffex'),
 ('Kiffu'),
 ('Kiilimaar'),
 ('Kile II'),
 ('Kilia IV'),
 ('Killaniri'),
 ('Kilmauls'),
 ('Kimanan'),
 ('King\'s Galquek'),
 ('Kinooine'),
 ('Kins'),
 ('Kintan'),
 ('Kintoni'),
 ('Kinyen'),
 ('Kip'),
 ('Kir'),
 ('Kira I'),
 ('Kira II'),
 ('Kira III'),
 ('Kira IV'),
 ('Kirdo III'),
 ('Kirian'),
 ('Kiribi'),
 ('Kirima'),
 ('Kirrek'),
 ('Kirtania'),
 ('Kirtarkin'),
 ('Kiskin'),
 ('Kismaano'),
 ('Kissarm'),
 ('Kiva'),
 ('Kktkt'),
 ('Klatooine'),
 ('Klatoon'),
 ('Klaymore 4-2'),
 ('Kleeva'),
 ('Kloper'),
 ('Kluistar'),
 ('Knolstee'),
 ('Knores'),
 ('Koaan'),
 ('Koba'),
 ('Kobal\'s World'),
 ('Kobbahn'),
 ('Koboth'),
 ('Koda'),
 ('Koda\'s World'),
 ('Kodai'),
 ('Kodasta'),
 ('Kogan 6'),
 ('Kojash'),
 ('Kol Huro I'),
 ('Kol Huro II'),
 ('Kol Huro III'),
 ('Kol Huro IV'),
 ('Kol Huro V'),
 ('Kol Huro VI'),
 ('Kol Huro VII'),
 ('Kolaador'),
 ('Kolatill'),
 ('Koli'),
 ('Kooda'),
 ('Kooriva'),
 ('Korad'),
 ('Koratas'),
 ('Korbin'),
 ('Korda 6'),
 ('Kordu'),
 ('Korev VII'),
 ('Korfin'),
 ('Korlings'),
 ('Kormoran'),
 ('Koros Minor'),
 ('Korphir'),
 ('Korriban'),
 ('Korriz'),
 ('Korseg IV'),
 ('Koru Neimoidia'),
 ('Koss'),
 ('Kostra'),
 ('Kothlis'),
 ('Kowak'),
 ('Krake\'s Planet'),
 ('Krann'),
 ('Krant'),
 ('Kraten'),
 ('Krayiss II'),
 ('Kreeling'),
 ('Krenhner'),
 ('Krevas'),
 ('Kriekaal'),
 ('Kril\'dor'),
 ('Krinemonen III'),
 ('Kriselist'),
 ('Krish'),
 ('Krizzin'),
 ('Krnay'),
 ('Kroctar'),
 ('Kromol'),
 ('Kromus'),
 ('Kronas'),
 ('Krykas V'),
 ('Krykis IV'),
 ('Krylon'),
 ('Ksiczzic III'),
 ('Ksift'),
 ('Ku\'Bakai 11'),
 ('Ku\'Bakai 6'),
 ('Ku\'Bakai 8'),
 ('Kuan'),
 ('Kuantar'),
 ('Kuar'),
 ('Kuat'),
 ('Kubindi'),
 ('Kuk\'tar'),
 ('Kulthis'),
 ('Kuminphal'),
 ('Kumru'),
 ('Kuna\'s Fist'),
 ('Kuna\'s Horn'),
 ('Kuna\'s Tail'),
 ('Kuna\'s Tooth'),
 ('Kur'),
 ('Kuras I'),
 ('Kuras II'),
 ('Kuras III'),
 ('Kuras IV'),
 ('Kushibah'),
 ('Kutag'),
 ('Kuthul'),
 ('Kvabja'),
 ('Kwannot'),
 ('Kwenn'),
 ('Kwevron'),
 ('Kwookrrr'),
 ('KyLessia'),
 ('Kyrouac'),
 ('Kyryll\'s World'),
 ('L\'at'),
 ('Laakteen Depot'),
 ('Laazrau'),
 ('Laboi II'),
 ('Lacia'),
 ('Ladarra'),
 ('Ladro'),
 ('Laertos'),
 ('Lafra'),
 ('Lahsbane'),
 ('Laim'),
 ('Lamarebb'),
 ('Lamarecc'),
 ('Lamaredd'),
 ('Lamaremm'),
 ('Lammax'),
 ('Lamuir IV'),
 ('Lamuir VII'),
 ('Lan Barell'),
 ('Lan Fellov'),
 ('Lan Tundi'),
 ('Langhesa'),
 ('Langoona'),
 ('Lankashiir'),
 ('Lannik'),
 ('Lansono'),
 ('Lanthe'),
 ('Lanthrym'),
 ('Lantillia'),
 ('Lao-mon'),
 ('Lapez-3'),
 ('Laramus'),
 ('Lasan'),
 ('Laseel'),
 ('Lastella'),
 ('Latharra'),
 ('Latoma'),
 ('Latt'),
 ('Laud'),
 ('Laut'),
 ('Lavisar'),
 ('Lazerian IV'),
 ('Lazerian IX'),
 ('Lazerian VI'),
 ('Lazerian VII'),
 ('Lefrani'),
 ('Lekua V'),
 ('Lelmra'),
 ('Lemmi VI'),
 ('Lennax'),
 ('Lenniera'),
 ('Lenthalis'),
 ('Lequabis'),
 ('Leria Kerlsil'),
 ('Leritor'),
 ('Lesser Galam'),
 ('Lessuris'),
 ('Lesu'),
 ('Letev'),
 ('Lethe'),
 ('Levian Two'),
 ('Leviathan'),
 ('Lexrol'),
 ('Lianna'),
 ('Licha In'),
 ('Liinade III'),
 ('Liintaar'),
 ('Lijuter'),
 ('Linuri'),
 ('Liok'),
 ('Lirra'),
 ('Lis'),
 ('Lisal'),
 ('Lish'),
 ('Listoria'),
 ('Little Capella'),
 ('Liyha'),
 ('Lo\'Uran'),
 ('Lobaoc'),
 ('Loce'),
 ('Lockest IV'),
 ('Logru'),
 ('Lohopa II'),
 ('Lok'),
 ('Lokondo'),
 ('Lol'),
 ('Lolnar'),
 ('Lomabu I'),
 ('Lomabu II'),
 ('Lomabu III'),
 ('Lomabu IV'),
 ('Lomabu V'),
 ('Lomabu VI'),
 ('Lonatro'),
 ('Londori'),
 ('Longwind'),
 ('Lonnaw'),
 ('Loovria'),
 ('Lorahns'),
 ('Lorardian'),
 ('Lorell'),
 ('Lorenz'),
 ('Loretto'),
 ('Lorimax'),
 ('Lorista'),
 ('Loronar'),
 ('Lorora'),
 ('Lorrad'),
 ('Lorrd'),
 ('Lors'),
 ('Lorta'),
 ('Lota'),
 ('Loth'),
 ('Lotide'),
 ('Low\'n'),
 ('Lowick'),
 ('Loxizhra'),
 ('Lucazec'),
 ('Lucrenn'),
 ('Lununmo'),
 ('Lupani'),
 ('Lurr'),
 ('Lusdu'),
 ('Lusk'),
 ('Lutrillia'),
 ('Luuq Two'),
 ('Luxior 7'),
 ('Lwhekk'),
 ('Lynaria'),
 ('Lynx'),
 ('Lyran IV'),
 ('Lythos Nine'),
 ('M\'Buh'),
 ('M\'haeli'),
 ('M2398-3'),
 ('M4-78'),
 ('Ma\'ar Shaddam'),
 ('Mabonte'),
 ('Maccent'),
 ('Mackar'),
 ('Maddules'),
 ('Maedano'),
 ('Magagran'),
 ('Magar\'s World'),
 ('Magresh'),
 ('Maires'),
 ('Mairne'),
 ('Majesticas'),
 ('Majilop'),
 ('Majoor'),
 ('Makem Dua'),
 ('Makem Hek'),
 ('Makem Liva'),
 ('Makem Pria'),
 ('Makem Qat'),
 ('Makem Sup'),
 ('Makem Te'),
 ('Makksre'),
 ('Makthierse'),
 ('Malachor V'),
 ('Malagarr'),
 ('Malanose'),
 ('Malastare'),
 ('Malavar'),
 ('Maldra IV'),
 ('Malicar 3'),
 ('Malkii'),
 ('Mall\'ordian'),
 ('Malo VI'),
 ('Malrev IV'),
 ('Malthor'),
 ('Mamendin'),
 ('Manaan'),
 ('Manalin'),
 ('Manari'),
 ('Manda'),
 ('Mandalore'),
 ('Mandell'),
 ('Mandrine'),
 ('Manforgon'),
 ('Mangez'),
 ('Manpha'),
 ('Manress'),
 ('Mantan'),
 ('Mantarran'),
 ('Mantessa'),
 ('Mantooine'),
 ('Manwess III'),
 ('Maphus Tria'),
 ('Mapuzo'),
 ('Mar\'ta I'),
 ('Mar\'ta II'),
 ('Maramere'),
 ('Marasai'),
 ('Marca'),
 ('Marenn Yagen'),
 ('Maridun'),
 ('Marjune'),
 ('Markon IV'),
 ('Marmoth'),
 ('Marngar III'),
 ('Maro Della'),
 ('Marotan'),
 ('Marquarra'),
 ('Maryx Minor'),
 ('Masalou'),
 ('Mastala'),
 ('Masterra'),
 ('Mataou'),
 ('Matra VI'),
 ('Mattri'),
 ('Mauk'),
 ('Mawan'),
 ('Maxca'),
 ('Maya Kovel'),
 ('Mayro'),
 ('Mazuma'),
 ('Meastrinnar'),
 ('Mechis III'),
 ('Medepiest'),
 ('Medth'),
 ('Megiddo'),
 ('Mekith'),
 ('Melasaton'),
 ('Melida/Daan'),
 ('Melinz'),
 ('Mengjini'),
 ('Menias'),
 ('Menkooro'),
 ('Mepha\'as Prime'),
 ('Mephitis'),
 ('Merakai'),
 ('Meridias'),
 ('Merikon'),
 ('Meris I'),
 ('Meris II'),
 ('Meris III'),
 ('Meris V'),
 ('Meris VI'),
 ('Merisee'),
 ('Merkat'),
 ('Merson'),
 ('Metacom'),
 ('Metalorn'),
 ('Metellos'),
 ('Mexeluine'),
 ('Midani'),
 ('Miglar 2'),
 ('Mijos'),
 ('Mikak'),
 ('Miko'),
 ('Mila'),
 ('Milagro'),
 ('Milarian'),
 ('Militar'),
 ('Millinar'),
 ('Milvayne'),
 ('Mim'),
 ('Mima II'),
 ('Mimban'),
 ('Minashee'),
 ('Mindabaal'),
 ('Mindavar'),
 ('Mindemir'),
 ('Mindor'),
 ('Minntaa'),
 ('Minntooine'),
 ('Mira'),
 ('Mirani'),
 ('Mirial'),
 ('Mirshaf'),
 ('Mirshilan'),
 ('Miser'),
 ('Miyuu'),
 ('Mizra'),
 ('Miztoc'),
 ('Mobus'),
 ('Moer'),
 ('Mokk IX'),
 ('Mol Luxu'),
 ('Moll'),
 ('Moltok'),
 ('Mon Bala'),
 ('Mon Calamari'),
 ('Mon Eron'),
 ('Mon Gazza'),
 ('Mon Torri IV'),
 ('Monastery'),
 ('Monfreen'),
 ('Monhudle'),
 ('Monor II'),
 ('Montitia'),
 ('Moorja'),
 ('Morado'),
 ('Moraices'),
 ('Moralan'),
 ('Moratrig'),
 ('Morcanth'),
 ('Mordagon'),
 ('Morellia'),
 ('Mores'),
 ('Morishim'),
 ('Morjakar'),
 ('Morning\'s Bell'),
 ('Moro Three'),
 ('Morr III'),
 ('Morseer'),
 ('Mortav'),
 ('Morvogodine'),
 ('Mos'),
 ('Mossak'),
 ('Motexx'),
 ('Moth'),
 ('Mourn'),
 ('Movris'),
 ('Mowgle'),
 ('Mozos'),
 ('Mrisst'),
 ('Mrlsst'),
 ('Mrykos'),
 ('Msst'),
 ('Mugaar'),
 ('Munlali Mafir'),
 ('Muntiadu'),
 ('Munto Codru'),
 ('Murkhana'),
 ('Murninkam'),
 ('Muscave'),
 ('Muskree'),
 ('Mussibir III'),
 ('Musson'),
 ('Mustafar'),
 ('Mutanda'),
 ('Mutar-Horan'),
 ('Muugrah'),
 ('Muunilinst'),
 ('Muzara'),
 ('Mycroft'),
 ('Mygeeto'),
 ('Myl Vlahu'),
 ('Mylok IV'),
 ('Myomar'),
 ('Myrkr'),
 ('Mytaranor'),
 ('Mytus VII'),
 ('N\'dian'),
 ('N\'ildwab'),
 ('N\'zoth'),
 ('Naalol'),
 ('Nabatu'),
 ('Naboo'),
 ('Nadiem'),
 ('Nagi'),
 ('Nahsu Minor'),
 ('Najarka'),
 ('Najiba'),
 ('Nak Shimor'),
 ('Nal Hutta'),
 ('Naldar'),
 ('Nalzin'),
 ('Nam Chorios'),
 ('Nam Priax'),
 ('Nam\'ta'),
 ('Namore'),
 ('Namra'),
 ('Nanta-Ri'),
 ('Nantama'),
 ('Nanth\'ri'),
 ('Naos'),
 ('Napan'),
 ('Nar'),
 ('Nar Bo Sholla'),
 ('Nar Hekka'),
 ('Nar Kreeta'),
 ('Narg'),
 ('Narigus III'),
 ('Narn IV'),
 ('Narth'),
 ('Narvath'),
 ('Nathas I'),
 ('Natinati'),
 ('Nativum'),
 ('Nauton IV'),
 ('Navlaas'),
 ('Nazzri'),
 ('NCW-781'),
 ('Neary'),
 ('Necropolis'),
 ('Nedij'),
 ('Needan'),
 ('Neelabi'),
 ('Neelanon'),
 ('Neelgaimon'),
 ('Neftali'),
 ('Neimoidia'),
 ('Nekotrig'),
 ('Nelfrus'),
 ('Nella'),
 ('Nellac Kram'),
 ('Nelvaan'),
 ('Nensil'),
 ('Nentan'),
 ('Neocomora'),
 ('Neona'),
 ('Nepe'),
 ('Nepoy'),
 ('Neree'),
 ('Nerit'),
 ('Neshtab'),
 ('Nessem'),
 ('Netolio'),
 ('Netta'),
 ('Neutra 4'),
 ('Nevoota'),
 ('New Agamar'),
 ('New Alderaan'),
 ('New Apsolon'),
 ('New Bakstre'),
 ('New Bornalex'),
 ('New Brigia'),
 ('New Canistel'),
 ('New Cov'),
 ('New Cylimba'),
 ('New Holgha'),
 ('New Holstice'),
 ('New Javis'),
 ('New Jinda'),
 ('New Plympto'),
 ('New Polokia'),
 ('New Ralltiir'),
 ('New Shella'),
 ('Nez Peron'),
 ('Nezni'),
 ('Nibiru'),
 ('Nichen'),
 ('Niddion'),
 ('Nieuth IV'),
 ('Nigel III'),
 ('Nigel IV'),
 ('Niian'),
 ('Nim Drovis'),
 ('Nimba 5'),
 ('Nimban'),
 ('Nimbia'),
 ('Ninn'),
 ('Ninzam VI'),
 ('Niran'),
 ('Nirauan'),
 ('Nishr'),
 ('Nista'),
 ('Nivek'),
 ('Nixor'),
 ('Nizon'),
 ('Nkllon'),
 ('Nod Kartha'),
 ('Noe\'ha\'on'),
 ('Nolar'),
 ('Noleria'),
 ('Noonar'),
 ('Noori'),
 ('Nopces Prime'),
 ('Nopsin'),
 ('Norah'),
 ('Norclune'),
 ('Nordra'),
 ('Norne'),
 ('Norulac'),
 ('Norval II'),
 ('Nosken'),
 ('Notak'),
 ('Nothar'),
 ('Nothoiin'),
 ('Notron'),
 ('Nouane'),
 ('Novor XIX'),
 ('Novor XVIII'),
 ('Novor XX'),
 ('Novor XXI'),
 ('Novor XXII'),
 ('Novor XXIII'),
 ('Novor XXIV'),
 ('Novor XXIX'),
 ('Novor XXV'),
 ('Novor XXVI'),
 ('Novor XXVII'),
 ('Novor XXVIII'),
 ('Novor XXX'),
 ('Novor XXXI'),
 ('Novor XXXII'),
 ('Novor XXXIII'),
 ('Nozquivor'),
 ('Nubia'),
 ('Nulan VI'),
 ('Null'),
 ('Nur'),
 ('Nuralee'),
 ('Nurstin'),
 ('Nushk'),
 ('Nuswatta'),
 ('Nwarcol Point'),
 ('Nyasko'),
 ('Nyny'),
 ('Nyrvona'),
 ('Nyssa'),
 ('Nysza III'),
 ('Obas'),
 ('Obelia'),
 ('Obica'),
 ('Obinipor'),
 ('Oblis'),
 ('Obredaan'),
 ('Obroa-held'),
 ('Obroa-skai'),
 ('Obulette'),
 ('Ockbur'),
 ('Odae Ripp'),
 ('Odik II'),
 ('Odos'),
 ('Odryn'),
 ('Oetrago'),
 ('Off-Canau'),
 ('Ogden Minor'),
 ('Ogem'),
 ('Ogoth Tiir'),
 ('Ohann'),
 ('Ohda'),
 ('Ohratuu'),
 ('Ojom'),
 ('Oko E'),
 ('Olabria'),
 ('Olanet'),
 ('Olanjii'),
 ('Old Mankoo'),
 ('Oligtaz'),
 ('Olunmor'),
 ('OM811'),
 ('OM812'),
 ('OM813'),
 ('OM814'),
 ('Omakaton'),
 ('Omar'),
 ('Omdrid'),
 ('Omeddyl'),
 ('Omiddelon III'),
 ('Omman'),
 ('Ompersan'),
 ('Omwat'),
 ('Onadax'),
 ('Onderon'),
 ('Ondus'),
 ('Ongella'),
 ('Onuf'),
 ('Ookbat'),
 ('Oolidi'),
 ('Oon Tien'),
 ('Ooo-sek'),
 ('Oor VII'),
 ('Oorn Tchis'),
 ('Ootoola'),
 ('Oovo'),
 ('Ophideraan'),
 ('Oplovis'),
 ('Or Tuma'),
 ('Oran-m'),
 ('Orax'),
 ('Ord Antalaha'),
 ('Ord Biniir'),
 ('Ord Bueri'),
 ('Ord Canfre'),
 ('Ord Cantrell'),
 ('Ord Cestus'),
 ('Ord Dorlass'),
 ('Ord Grovner'),
 ('Ord Ibanna'),
 ('Ord Janon'),
 ('Ord Klina'),
 ('Ord Lithone'),
 ('Ord Mantell'),
 ('Ord Mirit'),
 ('Ord Mynock'),
 ('Ord Namurt'),
 ('Ord Pardron'),
 ('Ord Radama'),
 ('Ord Sabaok'),
 ('Ord Sedra'),
 ('Ord Sigatt'),
 ('Ord Simres'),
 ('Ord Tasson'),
 ('Ord Tessebok'),
 ('Ord Thoden'),
 ('Ord Tiddell'),
 ('Ord Torrenze'),
 ('Ord Traga'),
 ('Ord Trasi'),
 ('Ord Varee'),
 ('Ord Vaug'),
 ('Ord Vaxal'),
 ('Ord Wylan'),
 ('Ord Zat'),
 ('Ord Zeuol'),
 ('Ordaj'),
 ('Ordnandell'),
 ('Ordo'),
 ('Orellon II'),
 ('Orflon'),
 ('Orin'),
 ('Orinackra'),
 ('Orinda'),
 ('Orion IV'),
 ('Oris'),
 ('Orleon'),
 ('Orline'),
 ('Orma'),
 ('Orn Kios'),
 ('Orooturoo'),
 ('Orroman'),
 ('Orron III'),
 ('Orryxia'),
 ('Orto'),
 ('Ortuna'),
 ('Orvax IV'),
 ('Osarian'),
 ('Oshetti IV'),
 ('Osirrag'),
 ('Oslumpex V'),
 ('Ossel II'),
 ('Osseriton'),
 ('Ossus'),
 ('Ota'),
 ('Othone'),
 ('Otranto'),
 ('Otunia'),
 ('Outer Los'),
 ('Outpost'),
 ('Ova'),
 ('Ovise I'),
 ('Ovise II'),
 ('Ovise III'),
 ('Ovise IV'),
 ('Ovise V'),
 ('Ovise VI'),
 ('Ozu'),
 ('Paarin Minor'),
 ('Paigu'),
 ('Pako Ramoon'),
 ('Pakrik Major'),
 ('Pakrik Minor'),
 ('Pakuuni'),
 ('Palanhi'),
 ('Pallaxides'),
 ('Pammant'),
 ('Panatha'),
 ('Panna'),
 ('Pantolomin'),
 ('Paonnid'),
 ('Paquallis III'),
 ('Paqwepori'),
 ('Parada'),
 ('Paramatan'),
 ('Parcellus Minor'),
 ('Parein II 4'),
 ('Parmel'),
 ('Parmic'),
 ('Parshoone'),
 ('Parthis'),
 ('Partold'),
 ('Pas\'sic'),
 ('Pasmin'),
 ('Patar'),
 ('Patch-4'),
 ('Pauc\'on'),
 ('Paulking XIV'),
 ('Pavia'),
 ('Pavilion'),
 ('Pavo Prime'),
 ('PDC3141-02'),
 ('Pedd Four'),
 ('Pedducis Chorios'),
 ('Peg Shar I'),
 ('Pehzehvar'),
 ('Peirs'),
 ('Pelagon'),
 ('Pelemax'),
 ('Pelgrin'),
 ('Pelicd'),
 ('Pella'),
 ('Pellastrallus'),
 ('Pelutt'),
 ('Pembric II'),
 ('Pencael IV'),
 ('Pendal'),
 ('Pendari'),
 ('Pendarr III'),
 ('Pengalan IV'),
 ('Penovia'),
 ('Peppel'),
 ('Peragus II'),
 ('Peregrine\'s Nest planet'),
 ('Pergitor'),
 ('Peridon\'s Folly'),
 ('Perilious'),
 ('Perilix'),
 ('Perithal VI'),
 ('Permeles'),
 ('Pernam Minor'),
 ('Pernella'),
 ('Pernicar'),
 ('Pesafvri'),
 ('Pesitiin'),
 ('Pesmemben IV'),
 ('Petrakis'),
 ('Phaeda'),
 ('Pharnas'),
 ('Phateem'),
 ('Phaylenn'),
 ('Phelarion'),
 ('Phemis'),
 ('Pheon'),
 ('Phindar'),
 ('Phiris'),
 ('Phlors Regina'),
 ('Phlors Rex'),
 ('Pho Ph\'eah'),
 ('Phoebus'),
 ('Phorliss'),
 ('Phoros'),
 ('Phracas'),
 ('Phraetiss'),
 ('Phu'),
 ('Picutorion'),
 ('Pii I'),
 ('Pii II'),
 ('Pii III'),
 ('Pii IV'),
 ('Pii V'),
 ('Pii VI'),
 ('Pii VII'),
 ('Pil Diller'),
 ('Pinoora'),
 ('Pirdia'),
 ('Pirik'),
 ('Pirin'),
 ('Piroket'),
 ('Pirol-5'),
 ('Pirralor'),
 ('Pitann'),
 ('Piton'),
 ('Pitrillistia'),
 ('Pkihantri'),
 ('Plagen'),
 ('Plah'),
 ('Planet of the Dead'),
 ('Platoril'),
 ('Plavin 6'),
 ('Plesstil'),
 ('Plexis'),
 ('Plintep'),
 ('Ploo'),
 ('Pochi'),
 ('Pocia'),
 ('Poderis'),
 ('Polana'),
 ('Polis Massa'),
 ('Polixi'),
 ('Pollillus'),
 ('Polmanar'),
 ('Polneye'),
 ('Polus'),
 ('Pomagra'),
 ('Por Raton'),
 ('Porchello'),
 ('Port Evokk'),
 ('Port Haven'),
 ('Port Jerrell'),
 ('Porus Vida'),
 ('Poviduze'),
 ('Poytta'),
 ('Pozzi'),
 ('Praadost II'),
 ('Praesitlyn'),
 ('Praidaw'),
 ('Prakess'),
 ('Prakith'),
 ('Praxlis'),
 ('Prazhi'),
 ('Prefsbelt IV'),
 ('Presteen'),
 ('Pria'),
 ('Prildaz'),
 ('Prima'),
 ('Primor'),
 ('Prishardia'),
 ('Prishella III'),
 ('Procopia'),
 ('Prolifera'),
 ('Proxima Dibal I'),
 ('Puloorn'),
 ('Pursin'),
 ('Pyjridi'),
 ('Pypin'),
 ('Pyr'),
 ('Pyria 6'),
 ('Pyros'),
 ('Pzob'),
 ('Q\'Maere'),
 ('Q\'mara'),
 ('Qalita Prime'),
 ('Qalydon'),
 ('Qasqi'),
 ('Qat Chrystac'),
 ('Qetix'),
 ('Qexis'),
 ('Qiaxx'),
 ('Qiilura'),
 ('Qixon'),
 ('Qlothos'),
 ('Qoribu'),
 ('Qretu 5'),
 ('Quadrant Seven'),
 ('Quaensan Prime'),
 ('Qualtrough'),
 ('Quanton'),
 ('Quas Killam'),
 ('Quellor'),
 ('Quenus'),
 ('Quermia'),
 ('Ques'),
 ('Questal'),
 ('Queyta'),
 ('Quian'),
 ('Quiberon V'),
 ('Quint'),
 ('Quockra-4'),
 ('Quyste'),
 ('R\'alla'),
 ('R\'terleD\'er'),
 ('R-duba'),
 ('Raamen'),
 ('Rabaan'),
 ('Radeon'),
 ('Radix'),
 ('Radnor'),
 ('Radra IV'),
 ('Raed-7'),
 ('Rafa III'),
 ('Rafa IV'),
 ('Rafa V'),
 ('Rafa XI'),
 ('Rafft'),
 ('Ragmar V'),
 ('Ragna III'),
 ('Ragnar VIII'),
 ('Rago'),
 ('Ragoon VI'),
 ('Rainboh'),
 ('Raisa'),
 ('Raithal'),
 ('Rakaa IV'),
 ('Rakata Prime'),
 ('Rake'),
 ('Rakrir'),
 ('Ralltiir'),
 ('Ralme IV'),
 ('Ramodi'),
 ('Rampa I'),
 ('Rampa II'),
 ('Randa'),
 ('Randon'),
 ('Randorn 2'),
 ('Rangorah'),
 ('Rannon'),
 ('Ranste'),
 ('Rantorin'),
 ('Rasapan'),
 ('Raskane IV'),
 ('Rasterous'),
 ('Rathalay'),
 ('Rattatak'),
 ('Ravaath'),
 ('Raxus II'),
 ('Raxus Prime'),
 ('Raxxa'),
 ('Reaper\'s World'),
 ('Rearqu 10'),
 ('Reboam'),
 ('Recopia'),
 ('Red Twins'),
 ('Redcap'),
 ('Redilos'),
 ('Reecee'),
 ('Reef'),
 ('Reega'),
 ('Reena'),
 ('Refgar'),
 ('Refnar'),
 ('Regar I'),
 ('Regar II'),
 ('Regel Eight'),
 ('Reginard'),
 ('Regolith Prime'),
 ('Regulgo'),
 ('Rehemsa'),
 ('Rehn'),
 ('Reigalius'),
 ('Rela'),
 ('Relarr'),
 ('Relkass'),
 ('Rellio'),
 ('Rellnas'),
 ('Reltooine'),
 ('Relus'),
 ('Remitik'),
 ('Rena'),
 ('Renas'),
 ('Renatasia III'),
 ('Renatasia IV'),
 ('Rend 5'),
 ('Rendili'),
 ('Renegg'),
 ('Renforia'),
 ('Renforra'),
 ('Renillis'),
 ('Renor'),
 ('Rentalles'),
 ('Reopi'),
 ('Repea'),
 ('Resht VII'),
 ('Resti Kel'),
 ('Retep III'),
 ('Retep IV'),
 ('Rett I'),
 ('Rett II'),
 ('Reuss VIII'),
 ('Revisse'),
 ('Revyia'),
 ('Reyna'),
 ('Reynon'),
 ('Reytha'),
 ('Rezi-9'),
 ('Rhamalai'),
 ('Rhamsis Callo'),
 ('Rhelg'),
 ('Rhen Var'),
 ('Rhiannon'),
 ('Rhilithan'),
 ('Rhinnal'),
 ('Rhommamool'),
 ('Rhydonni Prime'),
 ('Rianon'),
 ('Ricaldi'),
 ('Riesa'),
 ('Riflor'),
 ('Rigel 7'),
 ('Rigneldia II'),
 ('Rigoran'),
 ('Riileb'),
 ('Rijel-12'),
 ('Rim 3'),
 ('Rima'),
 ('Rimma 13'),
 ('Rindao'),
 ('Rinn'),
 ('Rintonne'),
 ('Riome'),
 ('Rion'),
 ('Rior'),
 ('Ripoblus'),
 ('Risban'),
 ('Risha'),
 ('Rishal'),
 ('Rishi'),
 ('Ristel'),
 ('Rivvidu'),
 ('Roche'),
 ('Rodaj'),
 ('Rodia'),
 ('Rodis'),
 ('Rol Two'),
 ('Roldalna'),
 ('Romar'),
 ('Romin'),
 ('Romm'),
 ('Ronay'),
 ('Rondai-2'),
 ('Ronika'),
 ('Ronyards'),
 ('Roon'),
 ('Roona'),
 ('Roonadan'),
 ('Ropagi II'),
 ('Rordak'),
 ('Rorgam'),
 ('Rotas V'),
 ('Rothana'),
 ('Rove'),
 ('Roxuli'),
 ('Rrulinn'),
 ('Ruan'),
 ('Ruby'),
 ('Rudrig'),
 ('Rue'),
 ('Ruhe'),
 ('Ruisto'),
 ('Runaway Prince'),
 ('Rustibar'),
 ('Rutal 4'),
 ('Rutan'),
 ('Ruten'),
 ('Ruuria'),
 ('Ruusan'),
 ('Rya'),
 ('Rydar II'),
 ('Rydonni Prime'),
 ('Ryl'),
 ('Ryloon'),
 ('Ryloth'),
 ('Rymm'),
 ('Ryoone'),
 ('Ryvellia'),
 ('Ryyk'),
 ('S\'krrr'),
 ('Saarn'),
 ('Sab Rufo'),
 ('Sabrix'),
 ('Saclas'),
 ('Sacorria'),
 ('Safe Home'),
 ('Saffalore'),
 ('Sagma'),
 ('Sagresh'),
 ('Saheelindeel'),
 ('Saijo'),
 ('Sajun'),
 ('Sakiya'),
 ('Saleeh'),
 ('Saleucami'),
 ('Salliche'),
 ('Salltine'),
 ('Saloch'),
 ('Saloch 2'),
 ('Saloth'),
 ('Salteract'),
 ('Samaria'),
 ('Samarine Province'),
 ('Sanbra'),
 ('Sanjin'),
 ('Santarine'),
 ('Sanyassa IV'),
 ('Sapella'),
 ('Sappire'),
 ('Sarafur'),
 ('Sarahwiee'),
 ('Sarapin'),
 ('Sardoran'),
 ('Sareet'),
 ('Sarka'),
 ('Sarko VI'),
 ('Sarranket'),
 ('Sarrelon I'),
 ('Sarrelon II'),
 ('Sarrelon III'),
 ('Sarrelon IV'),
 ('Sarrelon V'),
 ('Sarrelon VI'),
 ('Sarrish'),
 ('Sartoy'),
 ('Sarvchi'),
 ('Sasan'),
 ('Sat\'Skar'),
 ('Savrant'),
 ('Sayblohn'),
 ('Scillal'),
 ('Sebiris'),
 ('Sedesia'),
 ('Sedri'),
 ('Seezar\'s Planet'),
 ('Seffi'),
 ('Sefon'),
 ('Seft'),
 ('Seftek'),
 ('Seikosha'),
 ('Seitia Prime'),
 ('Selab'),
 ('Selaggis VI'),
 ('Seldibia'),
 ('Selenius VII'),
 ('Selgon'),
 ('Seline'),
 ('Sellasas'),
 ('Selnesh'),
 ('Selonia'),
 ('Seltaya'),
 ('Seltos'),
 ('Selvaris'),
 ('Sembla'),
 ('Senex'),
 ('Senna'),
 ('Sennatt'),
 ('Seoul 5'),
 ('Sep Elopor'),
 ('Sepan 8'),
 ('Sequal'),
 ('Serat'),
 ('Seregar'),
 ('Serenity'),
 ('Serenno'),
 ('Serias'),
 ('Sermeria'),
 ('Sern Prime'),
 ('Sernpidal'),
 ('Serob 6'),
 ('Serphidi'),
 ('Serpine'),
 ('Serrata'),
 ('Serroco'),
 ('Sesid'),
 ('Sessa'),
 ('Sestooine'),
 ('Sestria'),
 ('Seswenna'),
 ('Setolio'),
 ('Setor'),
 ('Sev Tok'),
 ('Sevarcos'),
 ('Sevetta'),
 ('Seylott'),
 ('Shadda-Bi-Boran'),
 ('Shador'),
 ('Shadren V'),
 ('Shalam'),
 ('Shallow March'),
 ('Shallow Reach'),
 ('Shalm'),
 ('Shalyvane'),
 ('Shar\'Ack'),
 ('Shatuun'),
 ('Shaum Hii'),
 ('Shawken'),
 ('Shawti'),
 ('Shaymore'),
 ('Shella'),
 ('Sheris'),
 ('Shesharile'),
 ('Sheva'),
 ('Shibric'),
 ('Shifa'),
 ('Shiffrin'),
 ('Shikitari'),
 ('Shili'),
 ('Shimia'),
 ('Shimmer'),
 ('Shinbone'),
 ('Shindra'),
 ('Shintel'),
 ('Shiva IV'),
 ('Shogun'),
 ('Shola'),
 ('Shopani'),
 ('Shownar'),
 ('Shron'),
 ('Shud'),
 ('Shuldene'),
 ('Shulstine V'),
 ('Shulxi'),
 ('Shumavar'),
 ('Shumogi'),
 ('Shusugaunt'),
 ('Sibisime'),
 ('Sif\'kric'),
 ('Sif-Uwana'),
 ('Sifuchi'),
 ('Sikurd'),
 ('Sileron'),
 ('Siluria III'),
 ('Simpla-12'),
 ('Simus Minor I'),
 ('Simus Minor II'),
 ('Sinal'),
 ('Sinded'),
 ('Sinkar'),
 ('Sinsang'),
 ('Sinton'),
 ('Sionia'),
 ('Sirdar'),
 ('Sirilla'),
 ('Sirpar'),
 ('Sisk'),
 ('Siskeen'),
 ('Sissubo'),
 ('Skako'),
 ('Skann'),
 ('Skartis'),
 ('Skeebo'),
 ('Skone'),
 ('Skor II'),
 ('Skorrupon'),
 ('Skuumaa'),
 ('Skye'),
 ('Skynara'),
 ('Slag'),
 ('Sleheyron'),
 ('Sljee'),
 ('Sluis Van'),
 ('Sluudren'),
 ('Smarck'),
 ('Smarteel'),
 ('Snake\'s Den'),
 ('Sneeve'),
 ('Socco'),
 ('Sochi'),
 ('Socorro'),
 ('Solacton'),
 ('Solaest'),
 ('Solag'),
 ('Solanus'),
 ('Solay'),
 ('Solem'),
 ('Sollace'),
 ('Somavva'),
 ('Somov Rit'),
 ('Sondarr'),
 ('Sooma'),
 ('Sorella'),
 ('Sorfina'),
 ('Sorimow'),
 ('Sorjus'),
 ('Sorl'),
 ('Soronia'),
 ('Sorotarr VI'),
 ('Sorrus'),
 ('Soterios'),
 ('Sotipe'),
 ('Soullex'),
 ('Soun IV'),
 ('Speco'),
 ('Spee'),
 ('Spefik'),
 ('Sperin'),
 ('Spice Terminus'),
 ('Spinax III'),
 ('Spindrift'),
 ('Spira'),
 ('Spirador'),
 ('Spoi'),
 ('Spuma'),
 ('Spunchina'),
 ('Sriluur'),
 ('Stalsinek IV'),
 ('Stassia'),
 ('Steelious'),
 ('Stend IV'),
 ('Stend VI'),
 ('Stennaros'),
 ('Stenness'),
 ('Stenos'),
 ('Stentat'),
 ('Stic'),
 ('Stieg'),
 ('Stindaron'),
 ('Stoga'),
 ('Storinal'),
 ('Storm'),
 ('Storthus'),
 ('Stovax'),
 ('Stronghold'),
 ('Suarbi 7'),
 ('Subterrel'),
 ('Sucharme'),
 ('Sufezz'),
 ('Sullumun'),
 ('Sullust'),
 ('Sulphor'),
 ('Sumarin'),
 ('Sump'),
 ('Sunaj IV'),
 ('Sundari'),
 ('Suolriep'),
 ('Surron'),
 ('Suurja'),
 ('Svivren'),
 ('Swarquen'),
 ('Swedlan'),
 ('Sweep'),
 ('Sy Myrth'),
 ('Syboona'),
 ('Syndaar'),
 ('Syned'),
 ('Syni IV'),
 ('Syvris'),
 ('T-4D'),
 ('Taanab'),
 ('Taboon'),
 ('Taboth'),
 ('Tahlboor'),
 ('Takornan'),
 ('Tala 9'),
 ('Talas'),
 ('Talasea'),
 ('Talay'),
 ('Talesia'),
 ('Talfaglio'),
 ('Talita'),
 ('Tallaan'),
 ('Tallakron'),
 ('Tallaso'),
 ('Tallek'),
 ('Talleles'),
 ('Talofan'),
 ('Taloraan'),
 ('Talravin'),
 ('Talu'),
 ('Talus'),
 ('Tamarin'),
 ('Tamazall'),
 ('Tamban'),
 ('Tamber'),
 ('Tamboon'),
 ('Tammar'),
 ('Tammuz-an'),
 ('Tanalou'),
 ('Tanatrig'),
 ('Tancon'),
 ('Tanda'),
 ('Tandankin'),
 ('Tandis Four'),
 ('Tanger'),
 ('Tangrene'),
 ('Tanjay IV'),
 ('Tantajoc V'),
 ('Tanthior'),
 ('Tantive IV'),
 ('Tantive V'),
 ('Tantra'),
 ('Tanya'),
 ('Tanzis'),
 ('Tao-Grant'),
 ('Taoska'),
 ('Tar Morden'),
 ('Tarabba Prime'),
 ('Taraloon'),
 ('Tarastra'),
 ('Targonn'),
 ('Tarhassan'),
 ('Taria II'),
 ('Taris'),
 ('Tarkin\'s Fang'),
 ('Tarnab'),
 ('Tarnooga'),
 ('Tarsa');
/*!40000 ALTER TABLE `biography_planet` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;


