/*
---------------------------------------------------------------------------------------
This source file is part of SWG:ANH (Star Wars Galaxies - A New Hope - Server Emulator)

For more information, visit http://www.swganh.com

Copyright (c) 2006 - 2010 The SWG:ANH Team
---------------------------------------------------------------------------------------
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
---------------------------------------------------------------------------------------
*/

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

use swganh;

--
-- Definition of table `creature_species`
--

DROP TABLE IF EXISTS `creature_species`;
CREATE TABLE `creature_species` (
  `id` bigint(20) NOT NULL,
  `name` char(255) default NULL,
  `species_internal_description` char(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `creature_species`
--

/*!40000 ALTER TABLE `creature_species` DISABLE KEYS */;
INSERT INTO `creature_species` (`id`,`name`,`species_internal_description`) VALUES
 (1,'dune_lizard','Dune Lizard'),
 (1000,'aged_lantern_bird','Lantern Bird'),
 (1001,'aggrivated_bordok_mare','Bordok'),
 (1002,'agrilat_plumed_rasp','Plumed Rasp'),
 (1003,'alpha_bolma','Bolma'),
 (1004,'alpha_veermok','Veermok'),
 (1005,'ancient_bull_rancor','Rancor'),
 (1006,'ancient_graul','Graul'),
 (1007,'ancient_reptilian_flier','Reptilian Flyer'),
 (1008,'angler','Angler'),
 (1009,'angler_bone','Angler'),
 (1010,'angler_hatchling','Angler'),
 (1011,'angler_recluse','Angler'),
 (1012,'angry_baz_nitch_avenger','Baz Nitch'),
 (1013,'arachne_drone','Angler'),
 (1014,'arachne_fleshripper','Angler'),
 (1015,'arachne_hatchling','Angler'),
 (1016,'arachne_warrior','Angler'),
 (1017,'arachne_webmaster','Angler'),
 (1018,'arachne_widow','Angler'),
 (1019,'baby_bol','Bol'),
 (1020,'bachelor_gualama','Gualama'),
 (1021,'bageraset','Bageraset'),
 (1022,'bageraset_bruiser','Bageraset'),
 (1023,'bantha','Bantha'),
 (1024,'bantha_bonecracker','Bantha'),
 (1025,'bark_mite','Bark Mite'),
 (1026,'bark_mite_burrower','Bark Mite'),
 (1027,'bark_mite_burrower_collector','Bark Mite'),
 (1028,'bark_mite_burrower_drone','Bark Mite'),
 (1029,'bark_mite_burrower_queen','Bark Mite'),
 (1030,'bark_mite_burrower_swarmling','Bark Mite'),
 (1031,'bark_mite_burrower_worker','Bark Mite'),
 (1032,'bark_mite_hatchling','Bark Mite'),
 (1033,'baz_nitch','Baz Nitch'),
 (1034,'bearded_jax','Bearded Jax'),
 (1035,'beserk_kahmurra','Murra'),
 (1036,'bile_drenched_quenker','Quenker'),
 (1037,'bio_engineered_angler','Angler'),
 (1038,'bio_engineered_bageraset','Bageraset'),
 (1039,'bio_engineered_bantha','Bantha'),
 (1040,'bio_engineered_bearded_jax','Bearded Jax'),
 (1041,'bio_engineered_blurrg','Blurrg'),
 (1042,'bio_engineered_boar_wolf','Boar Wolf'),
 (1043,'bio_engineered_bocatt','Bocatt'),
 (1044,'bio_engineered_bol','Bol'),
 (1045,'bio_engineered_bolle_bol','Bolle Bol'),
 (1046,'bio_engineered_bolma','Bolma'),
 (1047,'bio_engineered_bordok','Bordok'),
 (1048,'bio_engineered_brackaset','Brackaset'),
 (1049,'bio_engineered_carrion_spat','Carrion Spat'),
 (1050,'bio_engineered_choku','Choku'),
 (1051,'bio_engineered_cu_pa','Cu Pa'),
 (1052,'bio_engineered_dalyrake','Dalyrake'),
 (1053,'bio_engineered_dewback','Dewback'),
 (1054,'bio_engineered_dune_lizard','Dune Lizard'),
 (1055,'bio_engineered_durni','Durni'),
 (1056,'bio_engineered_eopie','Eopie'),
 (1057,'bio_engineered_falumpaset','Falumpaset'),
 (1058,'bio_engineered_fambaa','Fambaa'),
 (1059,'bio_engineered_gnort','Gnort'),
 (1060,'bio_engineered_graul','Graul'),
 (1061,'bio_engineered_gronda','Gronda'),
 (1062,'bio_engineered_gualama','Gualama'),
 (1063,'bio_engineered_guf_drolg','Guf Drolg'),
 (1064,'bio_engineered_gurnaset','Gurnaset'),
 (1065,'bio_engineered_gurreck','Gurreck'),
 (1066,'bio_engineered_hermit_spider','Hermit Spider'),
 (1067,'bio_engineered_huf_dun','Hut Dun'),
 (1068,'bio_engineered_huurton','Huurton'),
 (1069,'bio_engineered_ikopi','Ikopi'),
 (1070,'bio_engineered_kaadu','Kaadu'),
 (1071,'bio_engineered_kima','Kima'),
 (1072,'bio_engineered_kimogila','Kimogila'),
 (1073,'bio_engineered_kliknik','Kliknik'),
 (1074,'bio_engineered_krahbu','Krahbu'),
 (1075,'bio_engineered_kusak','Kusak'),
 (1076,'bio_engineered_kwi','Kwi'),
 (1077,'bio_engineered_langlatch','Langlatch'),
 (1078,'bio_engineered_malkloc','Malkloc'),
 (1079,'bio_engineered_mawgax','Mawgax'),
 (1080,'bio_engineered_merek','Merek'),
 (1081,'bio_engineered_mott','Mott'),
 (1082,'bio_engineered_murra','Murra'),
 (1083,'bio_engineered_narglatch','Narglatch'),
 (1084,'bio_engineered_piket','Piket'),
 (1085,'bio_engineered_pugoriss','Pugoriss'),
 (1086,'bio_engineered_rancor','Rancor'),
 (1087,'bio_engineered_roba','Roba'),
 (1088,'bio_engineered_ronto','Ronto'),
 (1089,'bio_engineered_sand_panther','Corellian Sand Panther'),
 (1090,'bio_engineered_sharnaff','Sharnaff'),
 (1091,'bio_engineered_shear_mite','Shear Mite'),
 (1092,'bio_engineered_slice_hound','Corellian Slice Hound'),
 (1093,'bio_engineered_snorbal','Snorbal'),
 (1094,'bio_engineered_squall','Squall'),
 (1095,'bio_engineered_swirl_prong','Swirl Prong'),
 (1096,'bio_engineered_thune','Thune'),
 (1097,'bio_engineered_torton','Torton'),
 (1098,'bio_engineered_tusk_cat','Tusk Cat'),
 (1099,'bio_engineered_tybis','Tybis'),
 (1100,'bio_engineered_veermok','Veermok'),
 (1101,'bio_engineered_verne','Verne'),
 (1102,'bio_engineered_vesp','Vesp'),
 (1103,'bio_engineered_vir_vur','Vir Vur'),
 (1104,'bio_engineered_woolamander','Woolamander'),
 (1105,'bio_engineered_zucca_boar','Zucca Boar'),
 (1106,'blister_rot_queen','Bark Mite'),
 (1107,'blood_drenched_merek_king','Merek'),
 (1108,'blood_frenzied_boar_wolf','Boar Wolf'),
 (1109,'blood_stained_merek','Merek'),
 (1110,'blood_thirsty_borgle','Borgle'),
 (1111,'bloodfanged_gackle_bat','Gackle Bat'),
 (1112,'bloodseeker_mite','Bark Mite'),
 (1113,'bloodseeker_mite_drone','Bark Mite'),
 (1114,'bloodseeker_mite_guardian','Bark Mite'),
 (1115,'bloodseeker_mite_hunter','Bark Mite'),
 (1116,'bloodseeker_mite_queen','Bark Mite'),
 (1117,'bloodseeker_mite_sanguine_hierarch','Bark Mite'),
 (1118,'blooming_jax','Bearded Jax'),
 (1119,'blurrg','Blurrg'),
 (1120,'blurrg_hunter','Blurrg'),
 (1121,'blurrg_pup','Blurrg'),
 (1122,'blurrg_raptor','Blurrg'),
 (1123,'blurrg_sand_crawler','Blurrg'),
 (1124,'blurrg_tracker','Blurrg'),
 (1125,'blushing_jax','Bearded Jax'),
 (1126,'boar_wolf','Boar Wolf'),
 (1127,'boar_wolf_cub','Boar Wolf'),
 (1128,'boar_wolf_ravager','Boar Wolf'),
 (1129,'bocatt','Bocatt'),
 (1130,'bocatt_diseased','Bocatt'),
 (1131,'bocatt_tormented','Bocatt'),
 (1132,'bol','Bol'),
 (1133,'bol_lesser_plains','Bol'),
 (1134,'bol_pack_runner','Bol'),
 (1135,'bol_swift_charger','Bol'),
 (1136,'bolle_bol','Bolle Bol'),
 (1137,'bolle_bol_bark_biter','Bolle Bol'),
 (1138,'bolle_bol_calf','Bolle Bol'),
 (1139,'bolle_bol_colt','Bolle Bol'),
 (1140,'bolle_bol_elder_pulverizer','Bolle Bol'),
 (1141,'bolle_bol_female','Bolle Bol'),
 (1142,'bolle_bol_herd_leader','Bolle Bol'),
 (1143,'bolle_bol_male','Bolle Bol'),
 (1144,'bolle_bol_stomper','Bolle Bol'),
 (1145,'bolma','Bolma'),
 (1146,'bolma_calf','Bolma'),
 (1147,'bolma_female','Bolma'),
 (1148,'bolma_male','Bolma'),
 (1149,'bolma_pack_master','Bolma'),
 (1150,'bolma_prime','Bolma'),
 (1151,'bolma_youth','Bolma'),
 (1152,'bordok_ancient','Bordok'),
 (1153,'bordok_foal','Bordok'),
 (1154,'bordok_herd_master','Bordok'),
 (1155,'bordok_mare','Bordok'),
 (1156,'borgle','Borgle'),
 (1157,'borgle_desert_roamer','Borgle'),
 (1158,'borgle_desert_runner','Borgle'),
 (1159,'borgle_harvester','Borgle'),
 (1160,'borgle_life_sapper','Borgle'),
 (1161,'borgle_matriarch','Borgle'),
 (1162,'borgle_protector','Borgle'),
 (1163,'bounding_jax','Bearded Jax'),
 (1164,'brackaset','Brackaset'),
 (1165,'brackaset_female','Brackaset'),
 (1166,'brackaset_lowlands','Brackaset'),
 (1167,'brackaset_male','Brackaset'),
 (1168,'bull_bantha','Bantha'),
 (1169,'bull_rancor','Rancor'),
 (1170,'canoid','Boar Wolf'),
 (1171,'canoid_hunter','Boar Wolf'),
 (1172,'canoid_pack_leader','Boar Wolf'),
 (1173,'canyon_krayt_dragon','Krayt Dragon'),
 (1174,'canyon_krayt_dragon_no_loot','Krayt Dragon'),
 (1175,'capper_spineflap','Capper Spineflap'),
 (1176,'capper_spineflap_drone','Capper Spineflap'),
 (1177,'carnivorous_nuna','Nuna'),
 (1178,'carrion_spat','Carrion Spat'),
 (1179,'carrion_spat_corpsereaver','Carrion Spat'),
 (1180,'cave_beetle','Rock Mite'),
 (1181,'cave_gaping_spider','Gaping Spider'),
 (1182,'cave_gaping_spider_broodling','Gaping Spider'),
 (1183,'cave_gaping_spider_hunter','Gaping Spider'),
 (1184,'cave_gaping_spider_queen','Gaping Spider'),
 (1185,'cave_gaping_spider_recluse','Gaping Spider'),
 (1186,'cave_gaping_spider_recluse_giant','Gaping Spider'),
 (1187,'cave_gaping_spider_recluse_queen','Gaping Spider'),
 (1188,'charred_krevol','Horned Krevol'),
 (1189,'choku','Choku'),
 (1190,'choku_female','Choku'),
 (1191,'choku_hunter','Choku'),
 (1192,'choku_male','Choku'),
 (1193,'choku_packmaster','Choku'),
 (1194,'choku_pup','Choku'),
 (1195,'chuba','Chuba'),
 (1196,'chuba_large','Chuba'),
 (1197,'clipped_fynock','Fynock'),
 (1198,'confused_wood_mite_hatchling','Bark Mite'),
 (1199,'corellian_butterfly','Corellian Butterfly'),
 (1200,'corellian_butterfly_defender','Corellian Butterfly'),
 (1201,'corellian_butterfly_drone','Corellian Butterfly'),
 (1202,'corellian_butterfly_drone_large','Corellian Butterfly'),
 (1203,'corellian_butterfly_monarch','Corellian Butterfly'),
 (1204,'corellian_butterfly_monarch_bloodthirsty','Corellian Butterfly'),
 (1205,'corellian_butterfly_warrior','Corellian Butterfly'),
 (1206,'corellian_butterfly_worker','Corellian Butterfly'),
 (1207,'cowardly_gurreck','Gurreck'),
 (1208,'craggy_bolma','Bolma'),
 (1209,'crazed_durni','Durni'),
 (1210,'crazed_gurk_destroyer','Gurk'),
 (1211,'crazed_gurreck','Gurreck'),
 (1212,'crazed_roba','Roba'),
 (1213,'crescent_rasp','Crowned Rasp'),
 (1214,'crimson_blurrg','Blurrg'),
 (1215,'crimson_sand_panther','Corellian Sand Panther'),
 (1216,'crystal_snake','Crystal Snake'),
 (1217,'crystal_snake_hooded','Crystal Snake'),
 (1218,'cu_pa','Cu Pa'),
 (1219,'cu_pa_wonderous','Cu Pa'),
 (1220,'cyst_covered_rot_guard','Bark Mite'),
 (1221,'dalyrake','Dalyrake'),
 (1222,'dalyrake_harvester','Dalyrake'),
 (1223,'dalyrake_matriarch','Dalyrake'),
 (1224,'dappled_gualama','Gualama'),
 (1225,'dashing_vir_vur','Vir Vur'),
 (1226,'deadly_forest_mite_guardian','Bark Mite'),
 (1227,'deadly_vesp','Vesp'),
 (1228,'death_watch_quenker','Quenker'),
 (1229,'decay_mite','Bark Mite'),
 (1230,'delirious_merek_avenger','Merek'),
 (1231,'deranged_mantigrue','Condor Dragon'),
 (1232,'deranged_squall','Squall'),
 (1233,'deranged_wrix','Gurreck'),
 (1234,'desert_eopie','Eopie'),
 (1235,'desert_gurreck_charger','Gurreck'),
 (1236,'desert_razorback','Zucca Boar'),
 (1237,'desert_razorback_felspur','Zucca Boar'),
 (1238,'desert_squill','Squill'),
 (1239,'desert_vesp','Vesp'),
 (1240,'desert_womprat','Womp Rat'),
 (1241,'devil_gulginaw','Gulginaw'),
 (1242,'dewback','Dewback'),
 (1243,'dewback_cannibal','Dewback'),
 (1244,'dewback_sandreaver','Dewback'),
 (1245,'dim_u_bantha','Bantha'),
 (1246,'dire_cat','Narglatch'),
 (1247,'dire_cat_feral_orphan','Narglatch'),
 (1248,'diseased_blurrg','Blurrg'),
 (1249,'diseased_nuna','Nuna'),
 (1250,'diseased_vrelt','Stintaril'),
 (1251,'diseased_vrelt_matriarch','Stintaril'),
 (1252,'disturbed_bolma','Bolma'),
 (1253,'docile_kahmurra','Murra'),
 (1254,'domestic_bageraset','Bageraset'),
 (1255,'domestic_bearded_jax','Bearded Jax'),
 (1256,'domestic_bol_mount','Bol'),
 (1257,'domestic_eopie','Eopie'),
 (1258,'domestic_falumpaset','Falumpaset'),
 (1259,'domestic_humbaba','Falumpaset'),
 (1260,'domestic_krahbu','Krahbu'),
 (1261,'domestic_tusk_cat','Tusk Cat'),
 (1262,'domesticated_blurrg','Blurrg'),
 (1263,'domesticated_brackaset','Brackaset'),
 (1264,'domesticated_gurnaset','Gurnaset'),
 (1265,'domesticated_kaadu','Kaadu'),
 (1266,'domesticated_merek','Merek'),
 (1267,'domesticated_mott','Mott'),
 (1268,'domesticated_snorbal','Snorbal'),
 (1269,'dragonet','Dune Lizard'),
 (1270,'dragonet_armodragon','Dune Lizard'),
 (1271,'dreaded_vir_vir','Vir Vur'),
 (1272,'dune_bantha','Bantha'),
 (1273,'dune_beetle','Rock Mite'),
 (1274,'dune_kimogila','Kimogila'),
 (1275,'dune_kimogilla','Kimogila'),
 (1276,'dune_lizard','Dune Lizard'),
 (1277,'dune_lizard_sunstained','Dune Lizard'),
 (1278,'dung_mite','Bark Mite'),
 (1279,'dung_mite_repugnant_crawler','Bark Mite'),
 (1280,'durni','Durni'),
 (1281,'durni_vehement_warrior','Durni'),
 (1282,'dusk_vir_vur','Vir Vur'),
 (1283,'dwarf_bantha','Bantha'),
 (1284,'dwarf_eopie','Eopie'),
 (1285,'dwarf_gronda','Gronda'),
 (1286,'dwarf_nuna','Dwarf Nuna'),
 (1287,'dwarf_nuna_drooling','Dwarf Nuna'),
 (1288,'elder_gualama','Gualama'),
 (1289,'elder_hanadak_matriarch','Hanadak'),
 (1290,'elder_pugoriss','Pugoriss'),
 (1291,'elder_snorbal_female','Snorbal'),
 (1292,'elder_snorbal_male','Snorbal'),
 (1293,'elder_squall','Squall'),
 (1294,'enraged_bull_rancor','Rancor'),
 (1295,'enraged_dune_kimogila','Kimogila'),
 (1296,'enraged_kimogila','Kimogila'),
 (1297,'enraged_rancor','Rancor'),
 (1298,'enraged_reptilian_flier','Reptilian Flyer'),
 (1299,'enraged_tabage_mother','Langlatch'),
 (1300,'enraged_tybis','Tybis'),
 (1301,'enraged_wood_mite_king','Bark Mite'),
 (1302,'eopie','Eopie'),
 (1303,'eopie_herdmaster','Eopie'),
 (1304,'erratic_swirl_prong','Swirl Prong'),
 (1305,'falumpaset','Falumpaset'),
 (1306,'falumpaset_plodding','Falumpaset'),
 (1307,'fambaa','Fambaa'),
 (1308,'fambaa_furious_devastator','Fambaa'),
 (1309,'famished_sludge_panther','Corellian Sand Panther'),
 (1310,'fanned_rawl','Fanned Rawl'),
 (1311,'feared_fynock_youth','Fynock'),
 (1312,'fearful_fynock_youth','Fynock'),
 (1313,'feeble_kima','Kima'),
 (1314,'female_dire_cat','Narglatch'),
 (1315,'female_forest_slice_hound','Corellian Slice Hound'),
 (1316,'female_grassland_slice_hound','Corellian Slice Hound'),
 (1317,'female_great_grass_plains_tusk_cat','Tusk Cat'),
 (1318,'female_kai_tok','Kai Tok'),
 (1319,'female_kwi','Kwi'),
 (1320,'female_mountain_squill','Squill'),
 (1321,'female_sand_panther','Corellian Sand Panther'),
 (1322,'female_slice_hound','Corellian Slice Hound'),
 (1323,'female_snorbal_calf','Snorbal'),
 (1324,'female_swamp_tusk_cat','Tusk Cat'),
 (1325,'feral_bantha','Bantha'),
 (1326,'feral_forest_mite_king','Bark Mite'),
 (1327,'feral_gurk','Gurk'),
 (1328,'feral_mutant_gackle_stalker','Gackle Bat'),
 (1329,'ferocious_kusak','Kusak'),
 (1330,'festering_dung_queen','Bark Mite'),
 (1331,'festering_squill','Squill'),
 (1332,'fierce_borgle','Borgle'),
 (1333,'fierce_piket_protector','Piket'),
 (1334,'flesh_eating_chuba','Chuba'),
 (1335,'flewt','Flewt'),
 (1336,'flewt_leviathan','Flewt'),
 (1337,'flit','Flit'),
 (1338,'flit_bloodsucker','Flit'),
 (1339,'flit_harasser','Flit'),
 (1340,'flit_lethargic_behemoth','Flit'),
 (1341,'flit_youth','Flit'),
 (1342,'flite_rasp','Flite Rasp'),
 (1343,'flite_rasp_large','Flite Rasp'),
 (1344,'foaming_vynock','Vynock'),
 (1345,'forest_mite','Bark Mite'),
 (1346,'forest_murra','Murra'),
 (1347,'forest_slice_hound','Corellian Slice Hound'),
 (1348,'frail_squall','Squall'),
 (1349,'frail_squall_meek_avenger','Squall'),
 (1350,'frenzied_choku','Choku'),
 (1351,'frenzied_fynock_guardian','Fynock'),
 (1352,'frenzied_graul','Graul'),
 (1353,'frenzied_kahmurra','Murra'),
 (1354,'frightened_borgle','Borgle'),
 (1355,'frightened_young_flewt','Flewt'),
 (1356,'fuzzy_jax','Bearded Jax'),
 (1357,'fynock','Fynock'),
 (1358,'gackle_bat','Gackle Bat'),
 (1359,'gackle_bat_hunter','Gackle Bat'),
 (1360,'gackle_bat_myrmidon_lord','Gackle Bat'),
 (1361,'gackle_bat_vampiric','Gackle Bat'),
 (1362,'gaping_spider','Gaping Spider'),
 (1363,'gaping_spider_broodling','Gaping Spider'),
 (1364,'gaping_spider_chasmal','Gaping Spider'),
 (1365,'gaping_spider_hunter','Gaping Spider'),
 (1366,'gaping_spider_queen','Gaping Spider'),
 (1367,'gaping_spider_recluse','Gaping Spider'),
 (1368,'gaping_spider_recluse_giant','Gaping Spider'),
 (1369,'gaping_spider_recluse_giant_kiin_dray','Gaping Spider'),
 (1370,'gaping_spider_recluse_queen','Gaping Spider'),
 (1371,'genetically_enhanced_kahmurra','Murra'),
 (1372,'geonosian_acklay_bunker_boss','Acklay'),
 (1373,'geonosian_enhanced_kwi','Kwi'),
 (1374,'geonosian_gaping_spider_fire','Gaping Spider'),
 (1375,'geonosian_kliknik_force_strong','Kliknik'),
 (1376,'geonosian_kliknik_force_weak','Kliknik'),
 (1377,'giant_angler','Angler'),
 (1378,'giant_baz_nitch','Baz Nitch'),
 (1379,'giant_canyon_krayt_dragon','Krayt Dragon'),
 (1380,'giant_carrion_spat','Carrion Spat'),
 (1381,'giant_crystal_snake','Crystal Snake'),
 (1382,'giant_dalyrake','Dalyrake'),
 (1383,'giant_decay_mite_harvester','Bark Mite'),
 (1384,'giant_decay_mite_hatchling','Bark Mite'),
 (1385,'giant_decay_mite_protector','Bark Mite'),
 (1386,'giant_decay_mite_queen','Bark Mite'),
 (1387,'giant_decay_mite_royal_guardian','Bark Mite'),
 (1388,'giant_decay_mite_sentry','Bark Mite'),
 (1389,'giant_decay_mite_soldier','Bark Mite'),
 (1390,'giant_dune_kimogila','Kimogila'),
 (1391,'giant_dune_kimogilla','Kimogila'),
 (1392,'giant_flit','Flit'),
 (1393,'giant_fynock','Fynock'),
 (1394,'giant_gackle_bat','Gackle Bat'),
 (1395,'giant_gubbur','Gubbur'),
 (1396,'giant_horned_krevol','Horned Krevol'),
 (1397,'giant_kimogila','Kimogila'),
 (1398,'giant_mawgax','Mawgax'),
 (1399,'giant_peko_peko','Peko Peko'),
 (1400,'giant_pharple','Pharple'),
 (1401,'giant_sand_beetle','Rock Mite'),
 (1402,'giant_sand_beetle_cave','Rock Mite'),
 (1403,'giant_spined_puc','Spined Puc'),
 (1404,'giant_spined_snake','Spined Snake'),
 (1405,'giant_stintaril','Stintaril'),
 (1406,'giant_tanc_mite','Tanc Mite'),
 (1407,'giant_veermok','Veermok'),
 (1408,'giant_worrt','Worrt'),
 (1409,'giga_flite_rasp','Flite Rasp'),
 (1410,'gleaming_lantern_bird','Lantern Bird'),
 (1411,'glutted_fynock_queen','Fynock'),
 (1412,'gnarled_bark_mite_queen','Bark Mite'),
 (1413,'gnarled_rancor','Rancor'),
 (1414,'gnort','Gnort'),
 (1415,'gnort_massive','Gnort'),
 (1416,'gorax','Gorax'),
 (1417,'gorax_matriarch','Gorax'),
 (1418,'gorg','Chuba'),
 (1419,'gorg_glutton','Chuba'),
 (1420,'gorge_vesp','Vesp'),
 (1421,'grand_wrix','Gurreck'),
 (1422,'grassland_slice_hound','Corellian Slice Hound'),
 (1423,'grassland_voritor_tracker','Voritor Lizard'),
 (1424,'graul','Graul'),
 (1425,'graul_mangler','Graul'),
 (1426,'graul_marauder','Graul'),
 (1427,'graul_mauler','Graul'),
 (1428,'great_borgle','Borgle'),
 (1429,'great_plains_stalker','Corellian Sand Panther'),
 (1430,'greater_desert_womprat','Womp Rat'),
 (1431,'greater_gulginaw','Gulginaw'),
 (1432,'greater_shaupaut','Shaupaut'),
 (1433,'greater_sludge_panther','Corellian Sand Panther'),
 (1434,'grizzled_bark_mite','Bark Mite'),
 (1435,'grizzled_dewback','Dewback'),
 (1436,'gronda','Gronda'),
 (1437,'gronda_elder','Gronda'),
 (1438,'gronda_juggernaut','Gronda'),
 (1439,'gronda_patriarch','Gronda'),
 (1440,'gualama','Gualama'),
 (1441,'gualama_patriarch','Gualama'),
 (1442,'gubbur','Gubbur'),
 (1443,'gubbur_bloated','Gubbur'),
 (1444,'guf_drolg','Guf Drolg'),
 (1445,'guf_drolg_female','Guf Drolg'),
 (1446,'gulginaw','Gulginaw'),
 (1447,'gungan_falumpaset','Falumpaset'),
 (1448,'gungan_fambaa','Fambaa'),
 (1449,'gungan_kaadu','Kaadu'),
 (1450,'gungan_veermok','Veermok'),
 (1451,'gurk','Gurk'),
 (1452,'gurk_gatherer','Gurk'),
 (1453,'gurk_loathsome_mangler','Gurk'),
 (1454,'gurk_tracker','Gurk'),
 (1455,'gurk_whelp','Gurk'),
 (1456,'gurnaset','Gurnaset'),
 (1457,'gurnaset_hatchling','Gurnaset'),
 (1458,'gurrcat','Tusk Cat'),
 (1459,'gurreck','Gurreck'),
 (1460,'gurreck_prowler','Gurreck'),
 (1461,'hanadak_ancient','Hanadak'),
 (1462,'hanadak_drifter','Hanadak'),
 (1463,'hermit_spider','Hermit Spider'),
 (1464,'hermit_spider_guard','Hermit Spider'),
 (1465,'hermit_spider_queen','Hermit Spider'),
 (1466,'highland_remmer','Remmer'),
 (1467,'hilltop_gurreck_hunter','Gurreck'),
 (1468,'hilltop_kima','Kima'),
 (1469,'horned_krevol','Horned Krevol'),
 (1470,'horned_rasp','Horned Rasp'),
 (1471,'horned_voritor_jungle_lizard','Voritor Lizard'),
 (1472,'hostile_thune_mother','Thune'),
 (1473,'howling_plumed_rasp','Plumed Rasp'),
 (1474,'howling_plumed_rasp_large','Plumed Rasp'),
 (1475,'huf_dun','Huf Dun'),
 (1476,'huf_dun_bull','Huf Dun'),
 (1477,'humbaba','Falumpaset'),
 (1478,'huurton','Huurton'),
 (1479,'huurton_bloodhunter','Huurton'),
 (1480,'huurton_howler','Huurton'),
 (1481,'huurton_huntress','Huurton'),
 (1482,'huurton_matron','Huurton'),
 (1483,'huurton_pup','Huurton'),
 (1484,'huurton_reaper','Huurton'),
 (1485,'huurton_stalker','Huurton'),
 (1486,'ikopi','Ikopi'),
 (1487,'ikopi_stag','Ikopi'),
 (1488,'ikopi_stout_stallion','Ikopi'),
 (1489,'imperial_veermok','Veermok'),
 (1490,'infant_brackaset','Brackaset'),
 (1491,'infant_graul','Graul'),
 (1492,'injured_kwi','Kwi'),
 (1493,'injured_purbole','Purbole'),
 (1494,'injured_verne','Verne'),
 (1495,'irate_flewt_matriarch','Flewt'),
 (1496,'jabbas_palace_rancor','Rancor'),
 (1497,'jax_bounding_dwarf','Bearded Jax'),
 (1498,'jundland_eopie','Eopie'),
 (1499,'jungle_fynock','Fynock'),
 (1500,'juvenile_canyon_krayt','Krayt Dragon'),
 (1501,'kaadu','Kaadu'),
 (1502,'kaadu_aggrivated_trampler','Kaadu'),
 (1503,'kaadu_female','Kaadu'),
 (1504,'kaadu_male','Kaadu'),
 (1505,'kaadu_motley','Kaadu'),
 (1506,'kahmurra','Murra'),
 (1507,'kahmurra_bio_engineer','Murra'),
 (1508,'kai_tok_bloodreaver','Kai Tok'),
 (1509,'kai_tok_prowler','Kai Tok'),
 (1510,'kai_tok_scavenger','Kai Tok'),
 (1511,'kai_tok_slayer','Kai Tok'),
 (1512,'kamurith_defiler','Voritor Lizard'),
 (1513,'kamurith_foul_desecrator','Voritor Lizard'),
 (1514,'kamurith_nocuous','Voritor Lizard'),
 (1515,'kamurith_snapper','Voritor Lizard'),
 (1516,'kima','Kima'),
 (1517,'kima_ferine_razorfang','Kima'),
 (1518,'kimogila','Kimogila'),
 (1519,'kimogila_hatchling','Kimogila'),
 (1520,'kinad_baz_nitch','Baz Nitch'),
 (1521,'king_merek_harvester','Merek'),
 (1522,'king_venom_nightspider','Hermit Spider'),
 (1523,'kliknik','Kliknik'),
 (1524,'kliknik_dark_defender','Kliknik'),
 (1525,'kliknik_dark_hunter','Kliknik'),
 (1526,'kliknik_dark_queen','Kliknik'),
 (1527,'kliknik_dark_warrior','Kliknik'),
 (1528,'kliknik_dark_worker','Kliknik'),
 (1529,'kliknik_defender','Kliknik'),
 (1530,'kliknik_hatchling','Kliknik'),
 (1531,'kliknik_hunter','Kliknik'),
 (1532,'kliknik_mantis','Kliknik'),
 (1533,'kliknik_queen','Kliknik'),
 (1534,'kliknik_queen_harvester','Kliknik'),
 (1535,'kliknik_scout','Kliknik'),
 (1536,'kliknik_shredder_guardian','Kliknik'),
 (1537,'kliknik_swarming','Kliknik'),
 (1538,'kliknik_warrior','Kliknik'),
 (1539,'kliknik_worker','Kliknik'),
 (1540,'knotted_krevol','Horned Krevol'),
 (1541,'krahbu','Krahbu'),
 (1542,'krayt_dragon_ancient','Krayt Dragon'),
 (1543,'kreetle','Tanc Mite'),
 (1544,'kreetle_death','Tanc Mite'),
 (1545,'kreetle_over','Tanc Mite'),
 (1546,'kreetle_swarming','Tanc Mite'),
 (1547,'kuppernug_female','Kuppernug'),
 (1548,'kuppernug_hatchling','Kuppernug'),
 (1549,'kuppernug_juvenile','Kuppernug'),
 (1550,'kuppernug_male','Kuppernug'),
 (1551,'kusak','Kusak'),
 (1552,'kusak_hunter','Kusak'),
 (1553,'kusak_mauler','Kusak'),
 (1554,'kusak_pup','Kusak'),
 (1555,'kusak_stalker','Kusak'),
 (1556,'kussak_hunter','Kusak'),
 (1557,'kwi','Kwi'),
 (1558,'langlatch_destroyer','Langlatch'),
 (1559,'langlatch_female','Langlatch'),
 (1560,'langlatch_hatchling','Langlatch'),
 (1561,'langlatch_hunter','Langlatch'),
 (1562,'langlatch_juvenile','Langlatch'),
 (1563,'langlatch_male','Langlatch'),
 (1564,'langlatch_marauder','Langlatch'),
 (1565,'lantern_bird','Lantern Bird'),
 (1566,'large_cave_beetle','Rock Mite'),
 (1567,'large_rock_beetle','Rock Mite'),
 (1568,'large_sand_beetle','Rock Mite'),
 (1569,'lesser_bocatt','Bocatt'),
 (1570,'lesser_desert_womprat','Womp Rat'),
 (1571,'lesser_dewback','Dewback'),
 (1572,'leviasquall','Squall'),
 (1573,'lice_ridden_remmer_queen','Remmer'),
 (1574,'lowland_salt_mynock','Mynock'),
 (1575,'lumbering_bolma','Bolma'),
 (1576,'lurking_angler','Angler'),
 (1577,'lurking_shear_mite','Shear Mite'),
 (1578,'mad_angler','Angler'),
 (1579,'majestic_plumed_rasp','Plumed Rasp'),
 (1580,'male_great_grass_plains_tusk_cat','Tusk Cat'),
 (1581,'male_kai_tok','Kai Tok'),
 (1582,'male_snorbal_calf','Snorbal'),
 (1583,'male_swamp_tusk_cat','Tusk Cat'),
 (1584,'malignant_squill','Squill'),
 (1585,'malkloc','Malkloc'),
 (1586,'malkloc_bull','Malkloc'),
 (1587,'malkloc_plainswalker','Malkloc'),
 (1588,'malkloc_plainswalker_female','Malkloc'),
 (1589,'malkloc_plainswalker_youth','Malkloc'),
 (1590,'mamien_ancient','Mamien'),
 (1591,'mamien_elder','Mamien'),
 (1592,'mamien_female','Mamien'),
 (1593,'mamien_junglelord','Mamien'),
 (1594,'mamien_male','Mamien'),
 (1595,'mamien_matriarch','Mamien'),
 (1596,'mamien_youth','Mamien'),
 (1597,'mammoth_bearded_jax','Bearded Jax'),
 (1598,'mammoth_thune','Thune'),
 (1599,'mantigrue_hunter','Condor Dragon'),
 (1600,'mantigrue_insane_berserker','Condor Dragon'),
 (1601,'mantigrue_night_stalker','Condor Dragon'),
 (1602,'mantigrue_reaper','Condor Dragon'),
 (1603,'mantigrue_screecher','Condor Dragon'),
 (1604,'matriarch_bantha','Bantha'),
 (1605,'mature_hanadak','Hanadak'),
 (1606,'mature_hanadak_rock_smasher','Hanadak'),
 (1607,'mature_reptilian_flier','Reptilian Flyer'),
 (1608,'mature_snorbal_female','Snorbal'),
 (1609,'mature_snorbal_male','Snorbal'),
 (1610,'mauler_veermok','Veermok'),
 (1611,'maverick_gualama','Gualama'),
 (1612,'mawgax_female','Mawgax'),
 (1613,'mawgax_male','Mawgax'),
 (1614,'mawgax_raptor','Mawgax'),
 (1615,'mawgax_youth','Mawgax'),
 (1616,'meager_tortur','Torton'),
 (1617,'merek_assassin','Merek'),
 (1618,'merek_cavern_creeper','Merek'),
 (1619,'merek_deaths_head','Merek'),
 (1620,'merek_harvester','Merek'),
 (1621,'midnight_vir_vur','Vir Vur'),
 (1622,'minor_gorax','Gorax'),
 (1623,'minor_gubbur','Gubbur'),
 (1624,'minor_guf_drolg','Guf Drolg'),
 (1625,'minor_sludge_panther','Corellian Sand Panther'),
 (1626,'minor_worrt','Worrt'),
 (1627,'mire_marauder','Corellian Sand Panther'),
 (1628,'mott','Mott'),
 (1629,'mott_bull','Mott'),
 (1630,'mott_calf','Mott'),
 (1631,'mottled_wrix','Gurreck'),
 (1632,'mound_mite','Rock Mite'),
 (1633,'mountain_dewback','Dewback'),
 (1634,'mountain_ikopi','Ikopi'),
 (1635,'mountain_krevol','Horned Krevol'),
 (1636,'mountain_murra','Murra'),
 (1637,'mountain_squill','Squill'),
 (1638,'mountain_squill_guardian','Squill'),
 (1639,'mountain_squill_hunter','Squill'),
 (1640,'mountain_torton','Torton'),
 (1641,'mountain_vesp','Vesp'),
 (1642,'mountain_worrt','Worrt'),
 (1643,'murra','Murra'),
 (1644,'mutant_bark_mite_giant','Bark Mite'),
 (1645,'mutant_bark_mite_hatchling','Bark Mite'),
 (1646,'mutant_bark_mite_queen','Bark Mite'),
 (1647,'mutant_bark_mite_soldier','Bark Mite'),
 (1648,'mutant_bark_mite_worker','Bark Mite'),
 (1649,'mutant_baz_nitch','Baz Nitch'),
 (1650,'mutant_rancor','Rancor'),
 (1651,'mutant_womprat','Womp Rat'),
 (1652,'mutated_kahmurra','Murra'),
 (1653,'mutated_krevol_clicker','Horned Krevol'),
 (1654,'narglatch','Narglatch'),
 (1655,'narglatch_cub','Narglatch'),
 (1656,'narglatch_female','Narglatch'),
 (1657,'narglatch_guardian','Narglatch'),
 (1658,'narglatch_hunter','Narglatch'),
 (1659,'narglatch_matriarch','Narglatch'),
 (1660,'nightsister_bull_rancor','Rancor'),
 (1661,'nightsister_enraged_bull_rancor','Rancor'),
 (1662,'nightsister_enraged_rancor','Rancor'),
 (1663,'nightsister_rancor','Rancor'),
 (1664,'nightspider','Hermit Spider'),
 (1665,'nightspider_aggressor','Hermit Spider'),
 (1666,'nightspider_poison_spitter','Hermit Spider'),
 (1667,'noxious_squill','Squill'),
 (1668,'noxious_vrelt_scavenger','Stintaril'),
 (1669,'nudfuh','Huf Dun'),
 (1670,'nuna','Nuna'),
 (1671,'nym_domesticated_gurk','Gurk'),
 (1672,'nym_kusak_guardian','Kusak'),
 (1673,'oozing_dung_royal_guardian','Bark Mite'),
 (1674,'paralope','Swirl Prong'),
 (1675,'paralope_acicular_defender','Swirl Prong'),
 (1676,'peko_peko','Peko Peko'),
 (1677,'peko_peko_albatross','Peko Peko'),
 (1678,'percussive_rasp','Horned Rasp'),
 (1679,'perlek','Perlek'),
 (1680,'perlek_ravager','Perlek'),
 (1681,'perlek_scavanger','Perlek'),
 (1682,'perlek_scavenger','Perlek'),
 (1683,'pharple','Pharple'),
 (1684,'pigmy_pugoriss','Pugoriss'),
 (1685,'piket','Piket'),
 (1686,'piket_enraged_defender','Piket'),
 (1687,'piket_longhorn','Piket'),
 (1688,'piket_longhorn_female','Piket'),
 (1689,'piket_plains_walker','Piket'),
 (1690,'plains_hunter','Tusk Cat'),
 (1691,'plumed_rasp','Plumed Rasp'),
 (1692,'poisonous_krevol_queen','Horned Krevol'),
 (1693,'potbellied_vrobal','Roba'),
 (1694,'pouncing_jax','Bearded Jax'),
 (1695,'pudgy_nudfuh','Huf Dun'),
 (1696,'pugoriss','Pugoriss'),
 (1697,'pugoriss_venerable_devourer','Pugoriss'),
 (1698,'puny_gackle_bat','Gackle Bat'),
 (1699,'puny_stintaril','Stintaril'),
 (1700,'puny_tanc_mite','Tanc Mite'),
 (1701,'purbole','Purbole'),
 (1702,'purbole_elder','Purbole'),
 (1703,'purbole_hunter','Purbole'),
 (1704,'purbole_relentless','Purbole'),
 (1705,'purbole_scout','Purbole'),
 (1706,'purbole_stalker','Purbole'),
 (1707,'purbole_youth','Purbole'),
 (1708,'puss_covered_decay_mite_soldier','Bark Mite'),
 (1709,'putrid_borgle','Borgle'),
 (1710,'putrid_decay_mite_hatchling','Bark Mite'),
 (1711,'putrid_decay_mite_hatchling_large','Bark Mite'),
 (1712,'queen_arachne','Angler'),
 (1713,'queen_merek_harvester','Merek'),
 (1714,'quenker','Quenker'),
 (1715,'quenker_ravager','Quenker'),
 (1716,'quenker_relic_reaper','Quenker'),
 (1717,'quenker_terrible','Quenker'),
 (1718,'quest_hero_of_tatooine_ferocious_beast','Zucca Boar'),
 (1719,'rabid_mutant_kahmurra','Murra'),
 (1720,'rabid_shaupaut','Shaupaut'),
 (1721,'rabid_squall','Squall'),
 (1722,'radiant_lantern_bird','Lantern Bird'),
 (1723,'rancid_remmer_warrior','Remmer'),
 (1724,'rancor','Rancor'),
 (1725,'rancor_monstrous_brute','Rancor'),
 (1726,'rancor_youth','Rancor'),
 (1727,'ravaging_gackle_bat','Gackle Bat'),
 (1728,'ravenous_rasp','Horned Rasp'),
 (1729,'ravenous_roba_stalker','Roba'),
 (1730,'ravenous_torton','Torton'),
 (1731,'rawl_deadly_hooded','Fanned Rawl'),
 (1732,'razor_cat_eviscerator','Corellian Sand Panther'),
 (1733,'rebel_tamed_gurrcat','Tusk Cat'),
 (1734,'rebel_tamed_huurton','Huurton'),
 (1735,'rebel_tamed_razor_cat','Corellian Sand Panther'),
 (1736,'rebel_tamed_slice_hound','Corellian Slice Hound'),
 (1737,'recluse_gurk_king','Gurk'),
 (1738,'reclusive_roba','Roba'),
 (1739,'reclusive_shear_mite','Shearmite'),
 (1740,'remmer_carrion_keeper','Remmer'),
 (1741,'remmer_dune_scavenger','Remmer'),
 (1742,'reptilian_flier','Reptilian Flyer'),
 (1743,'reptilian_life_stealer','Reptilian Flyer'),
 (1744,'rhoa_kwi','Kwi'),
 (1745,'rhoa_kwi_guardian','Kwi'),
 (1746,'rhoa_kwi_hunter','Kwi'),
 (1747,'rhoa_kwi_pack_leader','Kwi'),
 (1748,'rill','Dune Lizard'),
 (1749,'rill_tempest','Dune Lizard'),
 (1750,'riverside_sulfur_mynock','Mynock'),
 (1751,'roaming_bordok_stud','Bordok'),
 (1752,'roba','Roba'),
 (1753,'roba_female','Roba'),
 (1754,'roba_infuriated_protectorate','Roba'),
 (1755,'roba_male','Roba'),
 (1756,'roba_pack_leader','Roba'),
 (1757,'roba_runt','Roba'),
 (1758,'rock_beetle','Rock Mite'),
 (1759,'rock_beetle_cave','Rock Mite'),
 (1760,'rockmite','Rock Mite'),
 (1761,'rogue_bageraset','Bageraset'),
 (1762,'rogue_bantha','Bantha'),
 (1763,'rogue_falumpaset','Falumpaset'),
 (1764,'rogue_fambaa','Fambaa'),
 (1765,'ronto','Ronto'),
 (1766,'ronto_furious','Ronto'),
 (1767,'ronto_male','Ronto'),
 (1768,'rot_mite','Bark Mite'),
 (1769,'rotten_gut_remmer_king','Remmer'),
 (1770,'rotting_pustule_guard','Bark Mite'),
 (1771,'runty_pharple','Pharple'),
 (1772,'salt_mynock','Mynock'),
 (1773,'sand_beetle','Rock Mite'),
 (1774,'sand_panther','Corellian Sand Panther'),
 (1775,'sand_panther_cub','Corellian Sand Panther'),
 (1776,'sandy_spined_snake','Spined Snake'),
 (1777,'sap_covered_forest_mite_queen','Bark Mite'),
 (1778,'savage_flewt_queen','Flewt'),
 (1779,'savage_guf_drolg','Guf Drolg'),
 (1780,'savage_humbaba','Falumpaset'),
 (1781,'savage_pugoriss','Pugoriss'),
 (1782,'savage_quenker','Quenker'),
 (1783,'scavenger_rat','Womp Rat'),
 (1784,'scorched_krevol','Horned Krevol'),
 (1785,'screaming_kai_tok','Kai Tok'),
 (1786,'scyk','Dune Lizard'),
 (1787,'scyk_volatile','Dune Lizard'),
 (1788,'seething_bol_crusher','Bol'),
 (1789,'sentry_hermit_spider','Hermit Spider'),
 (1790,'sevorrt','Worrt'),
 (1791,'shaggy_gurk_youth','Gurk'),
 (1792,'shallow_torton','Torton'),
 (1793,'sharnaff','Sharnaff'),
 (1794,'sharnaff_bull','Sharnaff'),
 (1795,'sharnaff_reckless_ravager','Sharnaff'),
 (1796,'sharptooth_langlatch','Langlatch'),
 (1797,'shaupaut','Shaupaut'),
 (1798,'shaupaut_hunter','Shaupaut'),
 (1799,'shear_mite','Shear Mite'),
 (1800,'shear_mite_broodling','Shear Mite'),
 (1801,'shear_mite_hunter','Shear Mite'),
 (1802,'shear_mite_queen','Shear Mite'),
 (1803,'shear_mite_soilder','Shear Mite'),
 (1804,'shear_mite_soldier','Shear Mite'),
 (1805,'shimmering_lantern_bird','Lantern Bird'),
 (1806,'sickening_dung_mite_worker','Bark Mite'),
 (1807,'sickle_rasp','Horned Rasp'),
 (1808,'sickly_decay_mite_queen','Bark Mite'),
 (1809,'singing_mountain_clan_rancor','Rancor'),
 (1810,'skreeg_adolescent','Skreeg'),
 (1811,'skreeg_female','Skreeg'),
 (1812,'skreeg_gatherer','Skreeg'),
 (1813,'skreeg_hunter','Skreeg'),
 (1814,'skreeg_infant','Skreeg'),
 (1815,'skreeg_male','Skreeg'),
 (1816,'skreeg_ominous','Skreeg'),
 (1817,'skreeg_scout','Skreeg'),
 (1818,'skreeg_warrior','Skreeg'),
 (1819,'skreeg_warrior_elite','Skreeg'),
 (1820,'slice_hound','Corellian Slice Hound'),
 (1821,'slinking_voritor_hunter','Voritor Lizard'),
 (1822,'sludge_panther','Corellian Sand Panther'),
 (1823,'snorbal','Snorbal'),
 (1824,'snorbal_matriarch','Snorbal'),
 (1825,'snorbal_titanic_demolisher','Snorbal'),
 (1826,'song_rasp','Horned Rasp'),
 (1827,'spiked_krevol','Horned Krevol'),
 (1828,'spined_puc','Spined Puc'),
 (1829,'spined_puc_poison','Spined Puc'),
 (1830,'spined_snake','Spined Snake'),
 (1831,'spined_snake_recluse','Spined Snake'),
 (1832,'spineflap_gatherer','Capper Spineflap'),
 (1833,'spineflap_guard','Capper Spineflap'),
 (1834,'spineflap_handmaiden','Capper Spineflap'),
 (1835,'spineflap_queen','Capper Spineflap'),
 (1836,'spineflap_soldier','Capper Spineflap'),
 (1837,'spitting_rawl','Fanned Rawl'),
 (1838,'squall','Squall'),
 (1839,'squall_female','Squall'),
 (1840,'squall_male','Squall'),
 (1841,'squill','Squill'),
 (1842,'squill_deranged_ravisher','Squill'),
 (1843,'squill_great','Squill'),
 (1844,'startled_vrelt_mother','Stintaril'),
 (1845,'stintaril','Stintaril'),
 (1846,'stintaril_fleshstripper','Stintaril'),
 (1847,'stintaril_prowler','Stintaril'),
 (1848,'stintaril_ravager','Stintaril'),
 (1849,'stintaril_scavenger','Stintaril'),
 (1850,'stoneskin_hanadak','Hanadak'),
 (1851,'stormtrooper_dewback','Dewback'),
 (1852,'stunted_huf_dun','Huf Dun'),
 (1853,'stunted_woolamander','Woolamander'),
 (1854,'sulfur_pool_mynock','Mynock'),
 (1855,'surefoot_brackaset','Brackaset'),
 (1856,'swamp_gurrcat','Tusk Cat'),
 (1857,'swamp_humbaba','Falumpaset'),
 (1858,'swamp_stalker','Tusk Cat'),
 (1859,'swarming_lesser_dewback','Dewback'),
 (1860,'swirl_prong','Swirl Prong'),
 (1861,'swirl_prong_impaler','Swirl Prong'),
 (1862,'swirl_prong_pack_leader','Swirl Prong'),
 (1863,'tabage','Langlatch'),
 (1864,'tabage_protector','Langlatch'),
 (1865,'tabage_scavenger','Langlatch'),
 (1866,'tamed_kuppernug','Kuppernug'),
 (1867,'tanc_mite','Tanc Mite'),
 (1868,'tanc_mite_eviscerator','Tanc Mite'),
 (1869,'tanc_mite_warrior','Tanc Mite'),
 (1870,'tatooine_mynock','Mynock'),
 (1871,'tattered_torton','Torton'),
 (1872,'thune','Thune'),
 (1873,'thune_grassland_guardian','Thune'),
 (1874,'thune_herd_leader','Thune'),
 (1875,'timid_vir_vur','Vir Vur'),
 (1876,'torton','Torton'),
 (1877,'torton_pygmy_adolescent','Torton'),
 (1878,'torton_pygmy_adult','Torton'),
 (1879,'torton_pygmy_juvenile','Torton'),
 (1880,'torton_pygmy_matriarch','Torton'),
 (1881,'torton_pygmy_mature','Torton'),
 (1882,'torton_pygmy_protector','Torton'),
 (1883,'torton_voracious_patriarch','Torton'),
 (1884,'tortur','Torton'),
 (1885,'tortur_bull','Torton'),
 (1886,'toxic_merek_battlelord','Merek'),
 (1887,'tusken_bantha','Bantha'),
 (1888,'twilight_vir_vur','Vir Vur'),
 (1889,'tybis','Tybis'),
 (1890,'tybis_female','Tybis'),
 (1891,'tybis_grand','Tybis'),
 (1892,'tybis_male','Tybis'),
 (1893,'tybis_youth','Tybis'),
 (1894,'variegated_womprat','Womp Rat'),
 (1895,'veermok','Veermok'),
 (1896,'veermok_cannibal','Veermok'),
 (1897,'veermok_cave','Veermok'),
 (1898,'veermok_giant_cave','Veermok'),
 (1899,'veermok_guard','Veermok'),
 (1900,'veermok_guard_cave','Veermok'),
 (1901,'veermok_hunter','Veermok'),
 (1902,'veermok_ravager','Veermok'),
 (1903,'veermok_scavenger','Veermok'),
 (1904,'veermok_scout','Veermok'),
 (1905,'veermok_scout_cave','Veermok'),
 (1906,'veermok_sentry','Veermok'),
 (1907,'veermok_sentry_cave','Veermok'),
 (1908,'venom_filled_arachne','Angler'),
 (1909,'verne','Verne'),
 (1910,'verne_bull','Verne'),
 (1911,'verne_calf','Verne'),
 (1912,'vesp','Vesp'),
 (1913,'vesp_hunter','Vesp'),
 (1914,'vesp_scavanger','Vesp'),
 (1915,'vexed_voritor_lizard','Voritor Lizard'),
 (1916,'vicious_huf_dun','Huf Dun'),
 (1917,'vicious_squall','Squall'),
 (1918,'vine_rawl','Fanned Rawl'),
 (1919,'violent_krahbu','Krahbu'),
 (1920,'vir_vur','Vir Vur'),
 (1921,'vir_vur_toxic_slasher','Vir Vur'),
 (1922,'voracious_rasp','Horned Rasp'),
 (1923,'voritor_dasher','Voritor Lizard'),
 (1924,'voritor_lizard','Voritor Lizard'),
 (1925,'voritor_spiked_slasher','Voritor Lizard'),
 (1926,'vrelt','Stintaril'),
 (1927,'vrobal','Roba'),
 (1928,'vrobal_bull','Roba'),
 (1929,'vrobal_sow','Roba'),
 (1930,'vrobalet','Roba'),
 (1931,'vynock','Vynock'),
 (1932,'war_gronda','Gronda'),
 (1933,'warren_bol','Bol'),
 (1934,'warren_cyborg_bol','Bol'),
 (1935,'warren_cyborg_dunelizard','Dune Lizard'),
 (1936,'warren_cyborg_huurton','Huurton'),
 (1937,'warren_cyborg_slicehound','Corellian Slice Hound'),
 (1938,'warren_cyborg_tuskcat','Tusk Cat'),
 (1939,'warren_dunelizard','Dune Lizard'),
 (1940,'warren_huurton_fierce','Huurton'),
 (1941,'warren_huurton_hostile','Huurton'),
 (1942,'warren_huurton_savage','Huurton'),
 (1943,'warren_slicehound','Corellian Slice Hound'),
 (1944,'warren_sludgepanther','Corellian Sand Panther'),
 (1945,'warren_thune','Thune'),
 (1946,'warren_tuskcat','Tusk Cat'),
 (1947,'wasteland_cu_pa','Cu Pa'),
 (1948,'whisper_bird_female','Whisper Bird'),
 (1949,'whisper_bird_hatchling','Whisper Bird'),
 (1950,'whisper_bird_majestic','Whisper Bird'),
 (1951,'whisper_bird_male','Whisper Bird'),
 (1952,'wild_dune_boar','Zucca Boar'),
 (1953,'wolf_kima','Kima'),
 (1954,'womprat','Womp Rat'),
 (1955,'womprat_city','Womp Rat'),
 (1956,'womprat_plague','Womp Rat'),
 (1957,'wood_mite','Bark Mite'),
 (1958,'wood_mite_matriarch','Bark Mite'),
 (1959,'wood_mite_royal_guard','Bark Mite'),
 (1960,'wooded_paralope','Swirl Prong'),
 (1961,'woodland_gurreck','Gurreck'),
 (1962,'woodland_kima','Kima'),
 (1963,'woolamander','Woolamander'),
 (1964,'woolamander_gatherer','Woolamander'),
 (1965,'woolamander_harrower','Woolamander'),
 (1966,'woolamander_harvester','Woolamander'),
 (1967,'woolamander_reaper','Woolamander'),
 (1968,'wormed_vrobal','Roba'),
 (1969,'worrt','Worrt'),
 (1970,'worrt_gutbuster','Worrt'),
 (1971,'wrix','Gurreck'),
 (1972,'wrix_bloodstained_prowler','Gurreck'),
 (1973,'young_baz_nitch','Baz Nitch'),
 (1974,'young_borgle','Borgle'),
 (1975,'young_borgle_gruntling','Borgle'),
 (1976,'young_hanadak_rock_crusher','Hanadak'),
 (1977,'young_malkloc','Malkloc'),
 (1978,'young_mountain_squill','Squill'),
 (1979,'young_reptilian_flier','Reptilian Flyer'),
 (1980,'young_roba','Roba'),
 (1981,'young_spined_snake','Spined Snake'),
 (1982,'zucca_boar','Zucca Boar'),
 (1983,'zucca_boar_blight','Zucca Boar'),
 (1984,'rancor_pygmy','Rancor'),
 (1985,'slice_hound_vicious','Corellian Slice Hound'),
 (1986,'fanned_rawl_giant','Fanned Rawl'),
 (1987,'mutant_hermit_spider','Hermit Spider'),
 (1988,'aged_kimogila','Kimogila'),
 (1989,'adolescent_krayt_dragon','Krayt Dragon'),
 (1990,'langlatch_giant','Langlatch'),
 (1991,'veermok_pygmy','Veermok'),
 (1992,'zucca_boar_elder','Zucca Boar'),
 (1993,'kimogila_dwarf','Kimogila'),
 (1994,'krayt_dragon_grand','Krayt Dragon');
/*!40000 ALTER TABLE `creature_species` ENABLE KEYS */;


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;